slave/tests/hostnamectl/runtest.sh

Basic sanity test for hostnamectl

hostnamectl sanity test

---

slave/tests/localectl/runtest.sh

Basic sanity test for localectl

localectl sanity test

---

slave/tests/killmode/runtest.sh
slave/tests/killmode/trapka
slave/tests/killmode/trapka.sub

So, once again, hopefully pushed correctly this time..
Please close PR #4 .

killmode test

---

slave/tests/timedatectl/runtest.sh

Timedatectl

---

README.md
slave/bootstrap.sh

I tried to reproduce https://github.com/systemd/systemd/pull/4456#issuecomment-257065303
And that's not so obvious :-)
So, I fixed some small bugs and updated the `README`
@zonque , please  have a look

Various fixes

---

slave/system-tests.sh

fedorahosted.org was retired on 2017-03-01
Closes #11
@poettering , @keszybz please take a look

system-tests: use https://github.com/beakerlib/beakerlib.git

---

slave/bootstrap.sh

This should be merged and enabled after https://github.com/systemd/systemd/pull/6544
is merged.

bootstrap: switch to meson

---

slave/testsuite.sh

Execute all TEST-* test cases from the internal testsuite.
Right now only the latest test is skipped (TEST-24-UNIT-TESTS), as it keeps failing - I'll try to investigate later.

Internal testsuite

---

agent-control.py

I'll try to setup a working CI for this repo, so we can avoid all that manual testing before deploying any changes. I'll use this PR for testing as well, as I need to create a new project in the CentOS CI Jenkins for this.
~~Also, I'll finally refrain for pushing directly into master~~

CI for CentOS CI

---

agent-control.py
agent/testsuite.sh

See https://github.com/systemd/systemd/pull/11130

Skip flaky integration tests

---

agent/bootstrap.sh

In lights of recent issues with unbootable systems (e.g. https://github.com/systemd/systemd/pull/11178), it would make sense to do a basic sanity check if the new systemd is at least bootable before installing it to the SUT. This should provide precious debug information if something goes south and speed-up the feedback cycle a little bit.
Originally, I wanted to write a simple systemd-nspawn test case from scratch, but in the end using an existing case instead of reinventing the wheel makes more sense.
@evverx what do you think?

Do a basic sanity check before installing the new systemd

---

agent/bootstrap.sh

A few light touches to make the bootstrap debugging a bit more bearable.

Save the sanity check output into a separate file

---

agent/bootstrap.sh

In light of recent copr outages, let's add a backup repo mirror,
so we can mitigate the outage impact as much as possible
(Technical background: simple reposync executed every hour)

Add a copr repo mirror

---

agent-control.py

SIGTERM handler to fix cleanup in Jenkins
Jenkins' GitHub Pull Request Builder plugin sends SIGTERM to our script
when a PR branch is force-pushed, to cancel the current job and run a new
one. However, SIGTERM won't call AgentControl's destructor (__del__), which
returns the loaned node back to the pool.
To avoid this issue, let's move the cleanup code to the `finally`
section of the `try - except` block and raise a custom exception
when SIGTERM is caught.
I verified this manually on the systemd slave node and it correctly returns the loaned node back to the pool when killed by `SIGTERM`.

SIGTERM handler to fix cleanup in Jenkins

---

utils/generate-index.sh

Several *eye candy* improvements for the log index

Log index improvements

---

agent-control.py

Jenkins sends `SIGHUP` along with `SIGTERM`, so we need to catch it as well to properly return the machine back to Duffy pool.

agent-control: improve cleanup in Jenkins

---

agent-control.py

Ugly workaround for current Jenkin's behavior, where the signal
is sent several times under certain conditions. This is already
filed upstream, but the fix is still incomplete. Let's just
ignore SIGTERM/SIGHUP until the cleanup is complete.
https://issues.jenkins-ci.org/browse/JENKINS-17116?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

agent-control: another machine cleanup tweaks for Jenkins

---

agent-control.py
agent/bootstrap-rhel8.sh
agent/rhel-wrapper.sh
agent/testsuite-rhel8.sh

RHEL8 systemd uses different configuration options, so let's just follow the RHEL7 style and create pair of separate scripts to handle RHEL8.

rhel-only: add custom scripts for RHEL8 systemd package

---

agent/bootstrap-rhel8.sh
agent/bootstrap.sh

Thanks @keszybz for pointing this out.

meson: replace CFLAGS env variable with -Dc_args meson counterpart

---

agent/testsuite-rhel8.sh
agent/testsuite.sh

agent: re-enable TEST-10-ISSUE-2467

---

agent/testsuite.sh

Temporary hotfix for https://github.com/systemd/systemd/issues/11724

Temporary disable systemd-networkd-tests.py

---

agent/testsuite.sh

Fixed by systemd/systemd#11657

agent: reenable test_exec_privatenetwork

---

agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap.sh

Make the compilation slightly faster on SMP systems.

bootstrap: correctly determine # of CPUs for make

---

agent/testsuite-rhel8.sh

See:
systemd/systemd-centos-ci#78
lnykryn/systemd-rhel#315

testsuite: extend the parallelization to RHEL 8 as well

---

common/task-control.sh

Followup to 6c3964e676595f2640ae50699278c40fae0f9101

common: don't overwrite the start mark

---

vagrant/Vagrantfiles/Vagrantfile_arch
vagrant/vagrant-test.sh

Let's re-enable tests which have been fixed in upstream and fix several typos.

Vagrant tweaks & fixes

---

agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap.sh
agent/testsuite-rhel7.sh
vagrant/vagrant-test-sanitizers.sh

See https://github.com/koalaman/shellcheck/wiki/SC2144

tree-wide: don't use globs in bash conditions

---

vagrant/vagrant-build.sh

Accidentally found by systemd/systemd#12542

vagrant: don't wait indefinitely when VM reload goes south

---

agent-control.py

agent: correctly handle "out-of-resources" situation 

---

common/task-control.sh
common/utils.sh
vagrant/vagrant-build.sh
vagrant/vagrant-test-sanitizers.sh

Attempt to run the systemd-networkd testsuite under ASan&UBSan

---

agent/testsuite.sh

agent: skip integration tests for man-only PRs

---

vagrant/vagrant-test-sanitizers.sh

Continuation of #161
Fixes #164

vagrant: collect coredumps using coredumpctl in sanitizer runs

---

agent/bootstrap-rhel8.sh
agent/bootstrap.sh

Revert EPEL workarounds

---

vagrant/boxes/Vagrantfile_archlinux_systemd

Followup to 7a85134dc4eb36e3dbb1bd96686bbe5a7bb7177a
---
See: https://github.com/systemd/systemd/pull/13747#issuecomment-539961289

vagrant: pin meson to v0.51.2

---

agent/testsuite.sh
vagrant/boxes/Vagrantfile_archlinux_systemd
vagrant/vagrant-test-sanitizers.sh
vagrant/vagrant-test.sh

The latest snapshot introduced some missing dependencies and other run-time issues

Fix Vagrant images

---

jenkins/runners/systemd-pr-build-vagrant-sanitizers.sh
jenkins/runners/systemd-pr-build-vagrant.sh
vagrant/vagrant-setup.sh

This should, hopefully, reduce the flakiness in nested KVM, as we'll run it on a newer kernel.

Switch vagrant jobs to CentOS 8-stream

---

agent/bootstrap-rhel8.sh

This reverts commit 0a4c3d918e589afd7305f5d4cc19f2ac323f5111.
Fixes: #210

Revert "agent/rhel8: temporarily disable CodeReady repo"

---

agent/bootstrap.sh

Follow up to 554d394d23139fa24fd10ac0c0370d46a4ac70d7

agent: drop the multipath module from 'sanity' initrd as well

---

agent/testsuite.sh
vagrant/vagrant-test-sanitizers.sh
vagrant/vagrant-test.sh

Followup to 4257cba93444422c2d84ae7896302028c2619b07

agent/vagrant: correctly collect test journals

---

agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap.sh
agent/testsuite-rhel7.sh
agent/testsuite-rhel8.sh
agent/testsuite.sh
common/task-control.sh
common/utils.sh
utils/reposync.sh
vagrant/vagrant-ci-wrapper.sh
vagrant/vagrant-test.sh

Playground for https://github.com/systemd/systemd/pull/15433/

Reintroduce test parallelization

---

agent/bootstrap-rhel8.sh
agent/testsuite-rhel8.sh

Followup to 9fa5a34019cfbcaccad3a696a64701d5df1bdf30

agent/rhel8: propagate cgroup settings into each test VM

---

agent/bootstrap.sh

to catch compatibility issues with older meson versions

agent: use distro meson on CentOS 7

---

common/task-control.sh

We rely on a predictable $TESTDIR path for artifact collection. This got
somewhat broken, since during the setup phase we'd generate a random
$TESTDIR path for certain tests which would stick to them until the next
cleanup phase.

common: use a predictable $TESTDIR path

---

vagrant/vagrant-setup.sh

The reason why this workaround is even needed in the first place is that
the distro libk5crypto.so is built with the OpenSSL crypto backend
(--with-crypto-impl=openssl), which causes undefined symbol errors, as
the Vagrant's embedded OpenSSL is older than the distro one.
To workaround this, we compile a local version of libk5crypto.so using
the builtin crypto implementation (--with-crypto-impl=builtin). Let's
make this fact explicit and add some nice documentation, so my future
dumb me doesn't have to spend an hour debugging this mess (again).

vagrant: explicitly compile krb5 with the builtin crypto

---

agent/bootstrap-rhel8.sh
agent/bootstrap.sh

This reverts commit 9b3b5e6360d948833305841a6cf17cbead7eb361.

Revert "agent: temporarily comment out the internal EPEL metalink"

---

agent-control.py

Initial support for the non-x86_64 VMs in the CentOS CI pool. So far only provisioning for further testing.

Support alternative architectures provided by CentOS CI

---

agent/bootstrap-rhel8.sh
agent/bootstrap.sh
vagrant/bootstrap_scripts/arch.sh

C.f. https://github.com/systemd/systemd/pull/17599.

bootstrap: set -Dfuzz-tests=true

---

vagrant/vagrant-setup.sh

vagrant: bump Vagrant to 2.2.14

---

vagrant/boxes/Vagrantfile_archlinux_systemd
vagrant/vagrant-setup.sh
vagrant/vagrant-test-sanitizers.sh
vagrant/vagrant-test.sh

This reverts commit c6075d9389f2f541b5fc15849572b3590a6812d1.

Revert "vagrant: pin repositories to kernel 5.7.12 (2020-08-14)"

---

agent/testsuite.sh
common/task-control.sh
vagrant/test_scripts/test-arch.sh

This should allow us to keep the flake-related noise at minimum without
sacrificing the coverage.

Attempt to retry flaky tests

---

.github/workflows/linter.yml
agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap.sh
agent/testsuite-rhel7.sh
agent/testsuite-rhel8.sh
agent/testsuite.sh
common/utils.sh
jenkins/runners/vagrant-make-cache.sh
utils/artifacts-copy-file.sh
utils/generate-index.sh
vagrant/bootstrap_scripts/arch.sh
vagrant/test_scripts/test-arch-sanitizers-clang.sh
vagrant/test_scripts/test-arch.sh
vagrant/test_scripts/test-rawhide-selinux.sh
vagrant/vagrant-build.sh
vagrant/vagrant-ci-wrapper.sh
vagrant/vagrant-make-cache.sh

Also, introduce a GH Action for shellcheck/shfmt.

tree-wide: make shellcheck happy

---

vagrant/test_scripts/test-arch-sanitizers-clang.sh

Follow-up to systemd/systemd#18907.

vagrant: cover additional systemd components with sanitizers

---

vagrant/test_scripts/test-arch-sanitizers-clang.sh
vagrant/vagrant-build.sh

Follow-up to systemd/systemd#18946

vagrant: run TEST-22-TMPFILES under sanitizers

---

vagrant/bootstrap_scripts/rawhide-selinux.sh

This reverts commit 78b7118bf7c068f45cd8d8c15d62f5fb11b18873.
Fixes: #373

Revert "vagrant: work around systemd crash in Rawhide"

---

agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd
vagrant/boxes/Vagrantfile_rawhide_selinux

https://github.com/systemd/systemd/pull/19630

tree-wide: add python3-jinja2 build dependency

---

agent/bootstrap-rhel9.sh
agent/bootstrap.sh
agent/testsuite.sh

so we can run TEST-06-SELINUX as well.

agent: enable SELinux but set it to permissive

---

agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap-rhel9.sh
agent/bootstrap.sh
agent/testsuite-rhel7.sh
agent/testsuite-rhel8.sh
agent/testsuite-rhel9.sh
agent/testsuite.sh
common/utils.sh
vagrant/bootstrap_scripts/arch-sanitizers-clang.sh
vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh
vagrant/vagrant-build.sh
vagrant/vagrant-ci-wrapper.sh
vagrant/vagrant-setup.sh

and by trapping on EXIT we'd overwrite an existing EXIT handler, since
in bash we can have only one handler per signal.

common: trap on RETURN instead of EXIT since we're in a function 

---

vagrant/bootstrap_scripts/arch.sh
vagrant/boxes/Vagrantfile_archlinux_systemd
vagrant/vagrant-setup.sh

See: https://bugs.archlinux.org/task/71071

vagrant: temporarily skip libcap pkg upgrade 

---

jenkins/runners/upstream-cron-build.sh
jenkins/runners/upstream-vagrant-archlinux-sanitizers.sh

This reverts commit 94444c51d1cab796299a07032887d0facaacb4af.

Revert "jenkins: temporarily switch around sanitizer jobs"

---

vagrant/test_scripts/test-arch-sanitizers-clang.sh

This test has been timing out intermittently without any apparent
reason. Until the root cause is found out, let's skip this test under
sanitizers to reduce CI flakiness.
e.g.:
```
exec-dynamicuser-runtimedirectory3.service: About to execute /bin/sh -x -c 'test -d /run/test-exec_runtimedirectorypreserve'
exec-dynamicuser-runtimedirectory3.service: Forked /bin/sh as 62440
exec-dynamicuser-runtimedirectory3.service: Changed dead -> start
exec-dynamicuser-runtimedirectory2.service: Control group is empty.
dev-vda2.device: Changed dead -> tentative
systemd\x2dmeson\x2dbuild-test-tmpfs.mount: Deactivated successfully.
systemd\x2dmeson\x2dbuild-test-tmpfs.mount: Changed mounted -> dead
Test timeout when testing exec-dynamicuser-runtimedirectory3.service …
```

vagrant: temporarily disable test-execute under sanitizers

---

vagrant/vagrant-make-cache.sh

The Fedora Rawhide Vagrant boxes seem to be finally fixed.
See: https://pagure.io/cloud-sig/issue/340
Partially reverts: f982bd79f0f7d69998d30cc4f2f2128653b45f66
Fixes: #398

vagrant: drop the workaround for Rawhide images

---

vagrant/bootstrap_scripts/arch-sanitizers-clang.sh
vagrant/test_scripts/test-arch-sanitizers-clang.sh

as we might call the ASan-enabled binaries during the build phase.
Should fix the build failure in systemd/systemd#20294 (and other similar future PRs).

vagrant: configure the clang's ASan DSO during bootstrap

---

utils/reposync.sh

The respective Copr builders are finally up, so mirror the newly added
packages as well.

utils: sync ppc64le repos as well

---

agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

Install multipath tools

---

agent/bootstrap-rhel7.sh
agent/bootstrap-rhel8.sh
agent/bootstrap-rhel9.sh
agent/bootstrap.sh
common/task-control.sh
common/utils.sh

dnf and other network-using command sometimes suffer from intermittent
timeouts/fails which negatively affect CI results. Let's retry them a
couple of times to, hopefully, mitigate that.

agent: retry network-using commands on fail

---

vagrant/boxes/Vagrantfile_archlinux_systemd

needed by systemd/systemd#21454

vagrant: install libdwarf and libelf

---

vagrant/boxes/Vagrantfile_archlinux_systemd

Needed by systemd/systemd#21562.

vagrant: install wireguard-tools

---

agent/testsuite.sh

to avoid https://github.com/systemd/systemd/issues/21675#issuecomment-993524324

agent: rotate journal before running the networkd test suite

---

utils/reposync.sh

as the CentOS CI artifacts server (https://artifacts.ci.centos.org) will
be decommissioned in the future).

utils: store reposync's artifacts in Jenkins

---

vagrant/test_scripts/test-arch-coverage.sh

If the test logs contain lines like:
```
...systemd-resolved[735885]: profiling:/systemd-meson-build/src/shared/libsystemd-shared-250.a.p/base-filesystem.c.gcda:Cannot open
```
it means we're possibly missing some coverage since gcov can't write the stats,
usually due to the sandbox being too restrictive (e.g. ProtectSystem=yes,
ProtectHome=yes) or the $BUILD_DIR being inaccessible to non-root users.

vagrant(coverage): check for (possibly) missing coverage

---

agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

Introduced by https://github.com/systemd/systemd/pull/22563.

Install tpm2-tools & swtpm

---

vagrant/bootstrap_scripts/arch-coverage.sh

which contains fixes for multiple outstanding issues.

arch(coverage): use a different cpp-coveralls fork branch

---

agent/bootstrap.sh

See: https://pagure.io/centos-infra/issue/724

agent: temporarily work around the recent C8S repo issue

---

agent/bootstrap.sh

This reverts commit 295e9ad818a399577a9de5a8c6f7698eb383021d.

Revert "agent: temporarily work around the recent C8S repo issue"

---

vagrant/bootstrap_scripts/rawhide-selinux.sh
vagrant/boxes/Vagrantfile_rawhide_selinux

otherwise we might f-up the machine due to incompatible
policies/unlabeled system files.

vagrant(rawhide): set SELinux to permissive before installing systemd

---

vagrant/test_scripts/test-arch-sanitizers-clang.sh

To catch issues like https://github.com/systemd/systemd/issues/23317 as
well.

vagrant(arch): extend the ASan/UBSan test list a bit

---

agent/testsuite.sh
vagrant/test_scripts/test-arch-coverage.sh
vagrant/test_scripts/test-arch-sanitizers-clang.sh
vagrant/test_scripts/test-arch.sh

to help with #475 and other task run time related issues.

common: run each task with GNU time

---

vagrant/test_scripts/test-arch-sanitizers-clang.sh

Follow-up to 1eeab0fda47b21ff4931e4942a73ca06e90ca775, but for the
sanitizer run.

vagrant(upstream): run the networkd testsuite in parallel w/ sanitizers

---

agent/bootstrap-alt.sh
agent/testsuite-alt.sh
vagrant/test_scripts/test-arch-sanitizers-clang.sh

Also, add TEST-70 to the ppc64le run, which was accidentally omitted in
the previous PR.

test: run TEST-45, TEST-71, and TEST-73 under sanitizers

---

agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

Required by https://github.com/systemd/systemd/pull/24572.

tree-wide(upstream): install jq

---

agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

Required by https://github.com/systemd/systemd/pull/24570.

tree-wide(upstream): install nftables

---

agent/bootstrap-alt.sh

See: https://bugzilla.redhat.com/show_bug.cgi?id=2127370

agent(alt): temporarily downgrade clang to 14.0.0-1

---

agent/testsuite.sh

to work around intermittent QEMU issues.

agent(upstream): retry parallelized tasks on fail

---

agent/bootstrap-alt.sh
agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

Requested in https://github.com/systemd/systemd/pull/24944.

tree-wide(upstream): install mtools

---

vagrant/boxes/Vagrantfile_archlinux_systemd

Requested by https://github.com/systemd/systemd/pull/25686.

vagrant(arch): install erofs-utils

---

agent/bootstrap-alt.sh

This reverts commit 7d05a67ca495cdea8cbc7477c8087ffd6dbf2320.

Revert "agent(alt): temporarily downgrade clang to 14.0.0-1"

---

agent/bootstrap-rhel9.sh

since with 7.2.0 we get spurious timeouts in multiple tests.

agent(rhel9): temporarily downgrade QEMU to 7.1.0 

---

vagrant/boxes/Vagrantfile_archlinux_systemd

This reverts commit 9c1f12c1c952c8b811876156c6509bc85fc31cc7.

Revert "vagrant(arch): temporarily downgrade gnu-efi"

---

vagrant/test_scripts/test-arch-coverage.sh

As some unit tests switch between different UIDs, making the gcov metadata inaccessible for them.

arch(coverage): tweak $BUILD_DIR's ACLs before running unit tests

---

agent-control.py

agent-control: rework signal handling

---

agent/bootstrap-rhel9.sh
agent/testsuite-rhel9.sh

This reverts commit 98d1ff6ffb080dee1991d5eef58ca811942d8280.

Revert "agent(rhel9): temporarily downgrade QEMU to 7.1.0"

---

agent/bootstrap-alt.sh
agent/bootstrap.sh

See: https://github.com/systemd/systemd/pull/26641
Related: 4b5e217

agent(upstream): install python3-pyelftools

---

agent/testsuite-alt.sh

agent(alt): use unified cgroups in nspawn as well

---

jenkins/runners/vagrant-make-cache.sh

This reverts commit dd9ece5f704555c1e07aebe7e5cb6023317fc36b.

Revert "jenkins: disable the Rawhide SELinux job"

---

agent/bootstrap-alt.sh
agent/bootstrap.sh
vagrant/boxes/Vagrantfile_archlinux_systemd

For https://github.com/systemd/systemd/pull/28064#issuecomment-1599945252

tree-wide(upstream): install stress

---

vagrant/bootstrap_scripts/rawhide-selinux.sh
vagrant/boxes/Vagrantfile_rawhide_selinux

To make builddep work with dnf5 once again.

rawhide: install dnf5-plugins

---

vagrant/boxes/Vagrantfile_rawhide_selinux
vagrant/vagrantfiles/Vagrantfile_rawhide

Let's see if this triggers some new AVCs.

vagrant(rawhide): run with UEFI & TPM 2.0

---

jenkins/runners/upstream-centos8-stable.sh
jenkins/runners/upstream-centos8.sh
jenkins/runners/upstream-vagrant-archlinux-sanitizers-stable.sh
jenkins/runners/upstream-vagrant-archlinux-sanitizers.sh
jenkins/runners/upstream-vagrant-archlinux-stable.sh
jenkins/runners/upstream-vagrant-archlinux.sh

Skip running on PRs that contain only mkosi-related changes.

jenkins: don't run on mkosi-only PRs

---

agent-control.py
utils/kexec.sh

Let's factor out the kexec shell stuff into a helper script, to make it slightly more readable.

Don't kexec if we already run the latest installed kernel

---

agent/bootstrap-alt.sh
agent/bootstrap.sh
vagrant/boxes/archlinux_systemd.sh

For https://github.com/systemd/systemd/pull/29748.

upstream: install nvme-cli

---

agent/bootstrap-alt.sh
agent/bootstrap.sh
vagrant/boxes/archlinux_systemd.sh

Needed by https://github.com/systemd/systemd/pull/28658.

upstream: install PKCS#11 related utils

---

agent/bootstrap-rhel8.sh

agent(rhel8): pin kernel for the RHEL 8 job as well

---

common/utils.sh

QEMU intermittently crashes when running TCG VMs in AWS on C9S. Until that's resolved, let's add a simple wrapper around the QEMU binary that reruns the command in case it dies due to SIGSEGV.
See: https://issues.redhat.com/browse/RHEL-23844

common: work around intermittent QEMU segfaults in AWS

---

agent-control.py
jenkins/runners/upstream-coverage.sh
jenkins/runners/upstream-cron-build.sh
jenkins/runners/upstream-vagrant-archlinux-sanitizers-stable.sh
jenkins/runners/upstream-vagrant-archlinux-sanitizers.sh
jenkins/runners/upstream-vagrant-archlinux-stable.sh
jenkins/runners/upstream-vagrant-archlinux.sh
jenkins/runners/upstream-vagrant-rawhide-selinux.sh
jenkins/runners/vagrant-make-cache.sh
utils/kexec.sh
vagrant/boxes/Vagrantfile_archlinux_systemd
vagrant/boxes/Vagrantfile_rawhide_selinux
vagrant/test_scripts/test-arch.sh
vagrant/vagrant-make-cache.sh
vagrant/vagrant-setup.sh
vagrant/vagrantfiles/Vagrantfile_arch
vagrant/vagrantfiles/Vagrantfile_rawhide

So we won't get caught off guard when C8S is EOLed at the end of May.

Move (almost) all C8S jobs to C9S
