systemd/systemd-centos-ci

slave-control.py
sometimes connection to the duffy server does not return a node to use,
so sleep some seconds and retry
=> slave-control.py: loop to try to get a duffy node

slave/bootstrap.sh
systemd places D-Bus policy files in /usr by default: https://github.com/systemd/systemd/pull/4892
D-Bus supports this since 1.9.18, but
```
$ rpm -q dbus
dbus-1.6.12-17.el7.x86_64
```
Fixes:
```
...
systemd-resolved[22]: Failed to register name: Connection timed out
...
```
and so on
@haraldh , @zonque , please take a look
=> bootstrap: place D-Bus policy files in /etc

agent/bootstrap.sh
CentOS uses nfsnobody as UID/GID 65534.
Not tested. But I hope this fixes two warnings during build.
=> meson: fix nobody user and group

agent-control.py, agent/testsuite.sh
This PR introduces artifact exporting in the CentOS CI infrastructure. 
The shenanigans with the environment and rsync password files are necessary to make the directory structure on the [artifact server](http://artifacts.ci.centos.org/systemd/) at least a little bit pretty, and to not expose sensitive information (like rsync password). Nevertheless, the directory structure is still far from pretty, at least in my opinion (`systemd/<branch|commit|pr>/<log-folder>/<log-file>.log>`) but let's see how it's going to work out.
=> Support artifact exporting

agent/bootstrap.sh, agent/testsuite.sh
Let's try running the integration test suite under both systemd-nspawn and KVM.
=> Run the integration test suite under KVM as well

agent-control.py, agent/bootstrap.sh, agent/testsuite.sh
Let's collect more (hopefully) useful logs from the SUT.
Namely:
- meson logs
- complete `TEST-??-*` logs (on fail)
- system journal dump after each phase
=> Slightly expand our artifact collection

LICENSE.LGPL2.1, agent-control.py
I finally got to the next item from my TODO list, which is rewriting the current `agent-control.py` script. Apart from cleaning up the code a little, the main reasons, among others, were a proper SUT cleanup when a Jenkins job is aborted (e.g. due to a PR update) and a better support for artifacts exporting. 
As it's a pretty fundamental change to the CI codebase, I'd really appreciate if someone (cc @evverx ) could take a look at the code if it looks alright (I hope I didn't make things worse).
=> Complete `agent-control.py` rewrite

agent/bootstrap.sh
Some tests are marked as *unsafe*, as they change the environment - this
shouldn't be an issue, as we execute them in an isolated environment
=> Enable unsafe tests

agent/bootstrap.sh
The original initrd provided by CentOS is pretty old (v219) and causes
several intermittent issues during the sanity check. Regenerating the
initrd however requires the new systemd to be installed, so let's
reorder the phases to ensure it.
@evverx I looked into the possibility of generating the initrd without installing the new systemd beforehand, and even though it is possible by writing a custom dracut config similar to the [default one](https://github.com/dracutdevs/dracut/blob/master/dracut.conf.d/fedora.conf.example), I'd say it's more fragile than just installing the new systemd and running the sanity check right after that.
=> bootstrap: update the initrd before the sanity check

agent/bootstrap.sh, agent/testsuite.sh
Set timeouts for integration tests using QEMU/nspawn. This could have been done in Jenkins instead, but here we have more granular control about what and where the timeouts should be.
Also, I replaced the inline bash env variable syntax with exports, as it's more readable given the amount of env variable we're currently setting.
=> Set test timeouts

agent/testsuite.sh
This reverts commit 73abd1b52cdac5861419b6863045d56f83c75cde.
Let's reenable TEST-20-MAINPIDGAMES, as https://github.com/systemd/systemd/issues/11330 has been resolved.
=> Revert "Temporarily disable TEST-20-MAINPIDGAMES..."

agent-control.py, agent/bootstrap-rhel7.sh, agent/testsuite-rhel7.sh
As we'd like to use the CentOS CI to test downstream systemd (RHEL 7, https://github.com/lnykryn/systemd-rhel), so let's add modified versions of CI scripts to allow that. ~~To make things less complicated, they're in a separate folder and should be used as replacements of scripts in the `agent` folder.~~
=> Add modified script versions to allow downstream testing

agent/bootstrap-rhel7.sh, agent/testsuite-rhel7.sh
Integration tests on RHEL7 should be fixed by lnykryn/systemd-rhel#263.
=> rhel7: reenable integration tests

agent/bootstrap-rhel8.sh
On RHEL 8 the default sysusers config file is missing the
systemd-resolve user, which is created during systemd-resolved RPM
installation. As we're compiling systemd from the source, create the
user and group manually
=> rhel8: create systemd-resolve user & group

agent/testsuite-rhel8.sh
After resolving outstanding issues with RHEL8 and CentOS CI, the integration testsuite is finally working as expected.
Related PRs:
- https://github.com/lnykryn/systemd-rhel/pull/267
- https://github.com/lnykryn/systemd-rhel/pull/261
- https://github.com/lnykryn/systemd-rhel/pull/265
=> rhel8: re-enable integration testsuite

agent/testsuite-rhel8.sh, agent/testsuite.sh
`test/TEST-02-CRYPTSETUP` was disabled in CentOS CI due to its flakiness (see systemd/systemd#10093). In efforts to make it stable once again, I went ahead and tried to reproduce the original issue, however, without any success. I ran the test ~200 times on a baremetal CentOS 7 machine and few dozen times in a QEMU Arch VM (inside of a Vagrant KVM VM), both on the latest master, and the test passed in all cases.
I'm not sure if the original issue was fixed indirectly by some upstream commit or if I've been extremely lucky so far, but I'd re-enable this test to see if the issue is indeed resolved or if it reappears again.
=> testsuite: re-enable TEST-02-CRYPTSETUP

agent/bootstrap.sh, agent/testsuite-rhel7.sh, agent/testsuite.sh
Thanks to Yu's and Susant's efforts all known failures of the `systemd-networkd-tets.py` should be fixed. For now I'll re-enable it only for the "vanilla" CI (i.e. the baremetal CentOS 7), and if it remains stable I'd like to enable it in the Vagrant builds as well.
=> Re-enable systemd networkd tests

agent/testsuite-rhel8.sh
Should work since https://github.com/lnykryn/systemd-rhel/pull/288 was merged.
=> agent: re-enable test_exec_privatenetwork on RHEL8

agent/bootstrap-rhel7.sh, agent/testsuite-rhel7.sh, agent/testsuite-rhel8.sh
Right now the 'clean' phase is called only before the test execution,
which leaves stray loop devices in the system and causes issues in
subsequent tests.
=> agent/rhel: cleanup loop devices after tests as well

agent/testsuite.sh
This reverts commit 98aabf61d64f6757bd88df4b4f0396c085ecd3e6.
Fixed by systemd/systemd#11741
=> Revert "Temporary disable systemd-networkd-tests.py"

agent/testsuite-rhel8.sh, agent/testsuite.sh, vagrant/vagrant-test.sh
I added a new test in https://github.com/systemd/systemd/pull/11841,
and it runs in ~8s on my machine, ~17s with address sanitizer. But the
test fails on centos-ci after a 30s timeout.
=> Make test timeouts * 3

vagrant/vagrant-test.sh
TEST-24-UNIT-TESTS started failing intermittently due
to newly introduced fuzzers. Bump the QEMU timeout to
reflect this change.
---
Should `fix` https://github.com/systemd/systemd/pull/11887#issuecomment-469296378
=> vagrant: bump QEMU_TIMEOUT to 2000s

vagrant/vagrant-test.sh
This correctly cleans artifacts after a successful test, so
the final artifacts are not cluttered by useless journals.
=> vagrant: use 'clean-again' as the second cleanup phase

utils/reposync.sh
Due to past copr stability issues I introduced a CentOS CI repo mirror in #35 to make the CI more robust. However, the repo currently lives on my VPS, which is not optimal, even though it's been pretty stable so far. As the last missing dependency is finally present on the systemd slave machine, I can finally move the mirror-making mechanism to the CentOS CI infrastructure, which should make it (hopefully) more robust.
The script creates a local mirror of the [copr](https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci/) repository and then syncs it to the CentOS CI artifact server - http://artifacts.ci.centos.org/systemd/mrc0mmand-systemd-centos-ci/.
After this change, the respective parts of the [bootstrap scripts](https://github.com/systemd/systemd-centos-ci/blob/master/ag …
=> utils: add a reposync script

agent/bootstrap-rhel8.sh, agent/bootstrap.sh
Followup for #88. I tested the CentOS CI repo mirror locally and it works as expected.
=> agent: replace repo mirrors with the new CentOS CI one

common/utils.sh
Let's support git submodules in the [systemd](https://github.com/systemd/systemd) repo.
Fixes #90
=> common: initialize submodules when checking out a PR/commit

common/utils.sh
Let's fix cases when a **merge** ref doesn't exist, i.e. for already merged pull requests and draft pull requests. Fall back to the (hopefully) always present **head** ref in such cases.
Should fix cases like systemd/systemd#12265.
=> common: fall back to head ref when merge ref doesn't exist

agent-control.py
In several recent systemd runs I noticed a few fails due to missing `bash`. Even though it's a most likely an infrastructure *hiccup*, let's add a `bash` dependency as a precaution to reduce the false-negative job ratio.
=> agent-control: ensure we have bash installed

agent-control.py, agent/bootstrap-rhel7.sh, agent/bootstrap-rhel8.sh, agent/bootstrap.sh
Followup to #94, as in some cases we might get a machine with a previously polluted multipath device mounted. We already do similar cleanups in other scripts, so let's do it here as well.
=> agent-control: try to remove the git repo before cloning it

agent/testsuite-rhel8.sh, agent/testsuite.sh, vagrant/vagrant-test.sh
Let's show the first couple of errors from `ninja test` in the console log,
so one doesn't have to dig through the enormous meson testlog.txt file.
=> Call ninja test with --print-errorlogs for easier troubleshooting

agent-control.py, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-make-cache.sh, vagrant/vagrant-setup.sh
Let's update, rebuild, and cache Vagrant images, which we use in systemd CentOS CI.
This should have a pretty substantial performance impact, as the *setup* phase, which involves updating the base system & installing test and build dependencies usually takes ~10 minutes.
=> vagrant: introduce Vagrant image/box cache

vagrant/README.md, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers, vagrant/vagrant-build.sh, vagrant/vagrant-ci-wrapper.sh, vagrant/vagrant-test-sanitizers.sh
Let's experiment with ASan & UBSan on Arch. If it's feasible, make it part of our regular testing workflow, as Travis CI doesn't cover tests, which require a full-fledged VM.
=> Run tests on Arch Linux under ASan & UBSan

agent/bootstrap-rhel8.sh, agent/bootstrap.sh, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers, vagrant/vagrant-test-sanitizers.sh
Let's run TEST-01-BASIC under sanitizers to cover the systemd daemon as a whole plus its subcomponents (like systemd-udevd).
Fixes #103
=> vagrant: run TEST-01-BASIC under sanitizers

vagrant/vagrant-test-sanitizers.sh
This should address https://github.com/systemd/systemd-centos-ci/pull/104#issuecomment-491433636 which I accidentally dropped during debugging.
=> vagrant: skip QEMU run under sanitizers if the nspawn one failed

agent-control.py, vagrant/vagrant-ci-wrapper.sh
The result reporting may be quite confusing, as all Vagrant runs are
currently in one Jenkins job, so let's split them, to boost the readability
and performance.
This should also allow us to include systemd-networkd tests into both
jobs without waiting forever for results
=> vagrant: split Vagrant jobs to separate runs

agent/bootstrap-rhel8.sh, agent/bootstrap.sh, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers
When systemd/systemd#12519 gets merged, man pages will be built on-demand
only. Let's enable the man page generation explicitly, so we can test it
even after this change.
=> tree-wide: generate man pages by default

common/utils.sh
As `git describe` generates a particularly useless tag (which points to
a merge commit provided by the `merge` ref), let's dump the object
description as well, which includes top commits of both the PR and
target branches. This should give us a better idea what was actually
tested
---
Should help in situations like https://github.com/systemd/systemd/pull/12577#issuecomment-493582200
=> common: show commit description after checkout

vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-test.sh
Let's try to enable `systemd-networkd-tests.py` under Vagrant (and more specifically under Arch), so we can test the new network-related features as well. 
After recent CI tweaks the test should be almost as fast as its baremetal counterpart, so hopefully it won't slow down the entire Vagrant job too much.
=> vagrant: enable systemd-networkd tests

vagrant/vagrant-test.sh
The amount of unit tests in TEST-24-UNIT-TESTS rises slowly, but
steadily, and it started triggering the 10m timeout in systemd-nspawn.
Let's bump it to 15m
cc @yuwata
=> vagrant: bump the nspawn timeout to 15 minutes

vagrant/boxes/Vagrantfile_archlinux_systemd
This should allow us to run wireguard tests from the systemd-networkd
testsuite
Fixes #122
=> vagrant: install wireguard-arch package

agent/bootstrap-rhel8.sh, agent/bootstrap.sh
Originally, the meson logs were collected in the final EXIT handler with
the rest of the logs. However, as we use a relative path for them and we
change the CWD multiple times throughout the bootstrap process, the
relative path may become invalid (and it indeed does) during error
handling. Let's register a separate EXIT handler for this with an
absolute path, so we get the meson logs in all cases
=> agent: correctly collect meson logs

vagrant/boxes/Vagrantfile_archlinux_systemd
With this snapshot we should be able to stick with gcc-8 for a while
until the performance issues with gcc-9 are resolved
---
Supersedes #135
=> vagrant: temporarily pin the system repos to the 2019-06-17 snapshot

vagrant/vagrant-setup.sh
In certain cases we might encounter system with Vagrant installed, but
without the vagrant-libvirt plugin. Let's check for & install the plugin
in a separate condition to cover this scenario.
=> vagrant: check & install vagrant-libvirt separately

common/utils.sh
This should cover https://github.com/systemd/systemd/pull/12904#issuecomment-506778965, or at least a part of it, as adding the filename would be somewhat cumbersome (especially for the journal, as it's generated in the `EXIT` handler).
Some examples:
```
$ curl -q https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/928/artifact//systemd-centos-ci/artifacts_all/artifacts_HziRYX/vagrant-logs.MZE/vagrant-arch-sanitizers-gcc-testsuite.Q5G/systemd-networkd_sanitizers_FAIL.log | check_for_sanitizer_errors
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0test_glob (__main__.NetworkctlTests) ... ../src/shared/linux/ethtool.h:129:23: …
```
=> common: extract encountered sanitizer errors

agent/testsuite.sh, vagrant/vagrant-test.sh
This change is relevant mostly for the systemd-network testsuite, which
keeps growing and the original 30m timeout was simply not enough.
Fixes #140
=> agent/vagrant: extend timeout for other integration tests

agent/bootstrap.sh, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc
After @jakubjelinek's hint (thanks a lot for it) in https://github.com/systemd/systemd/issues/12997 I went through the sanitizer documentations again and learned something I managed to miss multiple times in the past. Originally, I put `-O0` everywhere as I thought other optimization levels would interfere with the sanitizers, causing potential false positives, break stack unwinding, etc. To my surprise, all sanitizer documentations recommend using at least `-O1` but with `-fno-omit-frame-pointer` to keep the stack unwinding untouched.
That being the case, let's use `-O1` for (almost) all systemd builds, which will have some performance impact during compilation, but this should be evened up (most likely several times) with a better runtime of the tests.
I noticed that `-Og` is basically …
=> tree-wide: use -O1 -fno-omit-frame-pointer when compiling systemd

jenkins/runners/systemd-pr-build-vagrant-sanitizers.sh, jenkins/runners/systemd-pr-build-vagrant.sh, jenkins/runners/systemd-pr-build.sh
@evverx 
Following the proposal in https://github.com/systemd/systemd/pull/13087, I've put together a few changes which should help with the CentOS CI overload issue.
Changes:
1)  I moved the inline build scripts from Jenkins into this repo, which should improve transparency
2) The gcc part of the `systemd-pr-build-vagrant-sanitizers` job should be now disabled in favor of the clang one, to (hopefully temporarily) free up some resources
3) I proposed a *PR filter* to filter out some out-of-scope PRs from being tested
The PR filter limits the scope of changes to these folders/files:
```
$ SCOPE_RX='(^(catalog|factory|hwdb|meson.*|network|[^\.].*\.d$|rules|src|test|units))'
$ ls -a | grep -E "$SCOPE_RX"
catalog
factory
hwdb
meson.build
meson_options.txt
modprobe.d
network
rules
src
sysctl.d …
```
=> Performance improvements

vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
Let's see how systemd fares with gcc 9.1.x once again, after the bunch of fixes & workaround.
=> Revert Arch Linux repo pin

vagrant/Vagrantfiles/Vagrantfile_arch
In some cases the just compiled revision may end up being unbootable,
and since we don't have access to the serial console of the VM, it's
more or less undebuggable. Let's do a simple sanity check before the
reboot itself (as we already do in the CentOS 7 job) to make
the debugging easier.
Fixes #149
=> vagrant: do a sanity boot check before reboot

vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc, vagrant/boxes/Vagrantfile_archlinux_systemd
Let's pass through host's `/dev/random` using virtio-rng to satisfy entropy-intensive tasks, like the new random seed stuff.
=> /dev/random shenanigans

vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc, vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-build.sh
In rare cases the `vagrant ssh` command dies unexpectedly (so far only
during the systemd-networkd testsuite) with EC 255. Let's add some
'hooks' to make this debuggable.
This, of course, works only if the sudden connection loss was just
intermittent. If the network gets completely broken, this won't work as
well.
=> vagrant: try to get a journal dump when ssh unexpectedly dies 

agent/bootstrap-rhel8.sh, agent/bootstrap.sh
RHEL 7.7 started shipping python3 package, which conflicts with python36
package from EPEL. After RHEL 7.7 GA the python36 (EPEL) package was removed,
however, there's still no CentOS 7.7 compose. In other words, there is no
way how to install python3 on CentOS 7 right now.
Let's temporarily workaround it using the EPEL archive
=> agent: install python36 from EPEL archive

agent/bootstrap.sh, agent/testsuite.sh, common/utils.sh, vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-test.sh
Fixes #160 
---
~~So far this shows only stack traces from all coredumps. Calling `bt full` on every coredump would be definitely handy, but right now this would be somewhat cumbersome, as `coredumpctl` doesn't allow overriding/editing the `$SYSTEMD_DEBUGGER` command line, and `.gdbinit` runs before the gdb is properly initialized with passed arguments (executable & coredump).~~
=> Collect potential coredumps after running the testsuite 

vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc, vagrant/vagrant-setup.sh, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
As nested KVM got much more stable in recent years, let's give it a try
and attempt to use it by default to speed up tests under Vagrant.
The nested KVM setup requires two steps:
1) Enable nested KVM on the host system (modprobe kvm_* nested=1)
2) Tell the vagrant-libvirt plugin to use it (domain.nested = true)
=> vagrant: enable nested KVM

agent/bootstrap-rhel8.sh, agent/bootstrap.sh
The latest meson version (0.52.0) introduced an issue, where the
configure/setup phase ends up in an endless loop. Until it's resolved,
let's pin meson to its last working version.
See: systemd/systemd#13742
=> agent: pin meson to v0.51.2

agent/bootstrap.sh
This uses the systemd-centos-ci COPR repo until the official libbpf
package is available in EPEL
=> agent: install libbpf-devel on CentOS 7

vagrant/boxes/Vagrantfile_archlinux_systemd
See: https://github.com/systemd/systemd/pull/13744
---
Theoretically, we could use the `bcc` AUR package, but as we'd have to compile it locally with all necessary dependencies, it's much easier and faster to just clone & compile libbpf-next directly. And as a benefit we'll always get the latest version!
=> vagrant: compile & install libbpf-next library

vagrant/boxes/Vagrantfile_archlinux_systemd
Fixes #174. I'll leave the `dhcpcd` thing untouched, for now, as it make sense until we're able to change the lease time of the DHCP daemon in libvirt.
=> Revert recent Vagrant workarounds

vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
The current "version" of the workaround caused some race conditions, especially in sanitizer runs. Let's try to make it a little bit more robust.
Originally, I wanted to use a separate net device with a static IP address to fix the issue once for all. Unfortunately, due to constellation of events and implementation details along the vagrant-libvirt plugin & Arch images, this is simply not possible, at least for now (`config.vm.network` directives fail with the current Arch images and using a static IP for the management netdev is impossible with the current libvirt/dnsmasq implementation).
=> vagrant: beef up the dhcpcd 'workaround' a little

vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-test-sanitizers.sh
Since October 21st the whole systemd-networkd testsuite is failing under sanitizers due to `Permission denied` errors when trying to execute binaries from the build dir:
```
======================================================================
ERROR: test_glob (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test-network/systemd-networkd-tests.py", line 461, in test_glob
self.wait_online(['test1:degraded'])
File "test/test-network/systemd-networkd-tests.py", line 364, in wait_online
output = check_output(*networkctl_cmd, 'status', link.split(':')[0])
File "test/test-network/systemd-networkd-tests.py", line 43, in check_output
return subprocess.check_output(command, universal_newlines=True, …
```
=> vagrant: debug & fix systemd-networkd testsuite

common/utils.sh
As mentioned in #179 dhcpcd started crashing intermittently in the
recent weeks with SIGABRT during exiting. Even though it has no (at
least known) effect on the testsuite itself, it taints the coredumpctl
check. Let's add it temporarily to the ignore list, until it's
investigated and possibly fixed.
=> common: add dhcpcd to coredumpctl-check's ignore list

agent/bootstrap.sh, vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc
```
CFLAGS=-O1 => --optimization=1
CFLAGS=-g  => --buildtype=debug
```
---
See: https://github.com/systemd/systemd/issues/13742#issuecomment-549059700
=> tree-wide: replace certain CFLAGS with their native meson options

vagrant/Vagrantfiles/Vagrantfile_arch, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-clang, vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc
The *default* settings weren't much reliable, especially during the systemd-networkd teststuite, which messes around with the routes. Hopefully, this will make them a little bit more reliable.
=> vagrant: make the ssh connection a little bit more reliable

agent-control.py, jenkins/runners/systemd-rhel8-pr-build.sh
Also, switch the RHEL 8 job to CentOS 8-stream, as it should provide slightly newer packages than a *standard* CentOS 8.
=> agent-control: support CentOS 8-Stream

vagrant/vagrant-setup.sh, vagrant/vagrantfiles/Vagrantfile_arch
This should make the share more reliable and should also fix
compatibility issues with newer NFS versions (like v4) which don't
support UDP transport anymore.
=> vagrant: use TCP instead of UDP for NFS

jenkins/runners/systemd-rhel8-pr-build.sh
CentOS 8-stream has empty source repositories, which breaks the CI
during the `dnf builddep` phase. Switch back to CentOS 8 for now, to
mitigate this.
See:
https://bugs.centos.org/view.php?id=16715
https://lists.centos.org/pipermail/ci-users/2019-November/000981.html
=> jenkins: switch the RHEL 8 job back to CentOS 8

vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
The test has been pretty unstable for a while, consequently since the
nested KVM was enabled. As the test still runs on the *bare* CentOS,
let's disable it in Vagrant jobs to make them more reliable.
=> vagrant: disable test-journal-flush on nested KVM

agent/bootstrap.sh
systemd-homed requires (among others) libfdisk, which is not present on
CentOS 7. As it's already being tested by the Arch Linux job, let's skip
it here.
=> agent: disable systemd-homed in the CentOS 7 upstream job

vagrant/vagrant-setup.sh
As Vagrant uses NFS for its shared folders, we need a working nfsd on
the host machine. So far we always left the responsibility on the
provisioner, but experience showed the nfsd is not always up when we
need it. Let's enable & start it explicitly to make sure we have a
working nfsd before playing around with Vagrant.
=> vagrant: configure nfsd explicitly

agent/bootstrap.sh, vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh, vagrant/bootstrap_scripts/arch.sh, vagrant/vagrantfiles/Vagrantfile_arch
1) Switch to `--optimization=g`, as `--optimization=1` strips too much useful debugging metadata
2) Yet another NFS stability *improvements*
=> Usability improvements

vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-setup.sh
This should, theoretically & hopefully, fix the race condition, where
systemd compilation on NFS inside the Vagrant VM sporadically dies with:
archlinux_systemd_ci: /usr/bin/ld: error: /build/build/src/udev/libudev.so.1: file too short
=> vagrant: install & setup NTP (chrony) on both host & guest machines

vagrant/boxes/Vagrantfile_archlinux_systemd
See: https://github.com/systemd/systemd/issues/14548
=> vagrant: temporarily pin libcap to v2.28

agent/bootstrap-rhel8.sh
Currently the repository contains a package conflict, which breaks the
installation of systemd build dependencies:
```
enabling AppStream-source repository
enabling BaseOS-source repository
enabling extras-source repository
enabling epel-modular-source repository
enabling epel-source repository
Last metadata expiration check: 0:00:38 ago on Mon 13 Jan 2020 04:21:26 PM GMT.
Package gettext-0.19.8.1-17.el8.x86_64 is already installed.
Package git-2.18.1-4.el8.x86_64 is already installed.
Package gawk-4.2.1-1.el8.x86_64 is already installed.
Package xz-5.2.4-3.el8.x86_64 is already installed.
Package firewalld-filesystem-0.7.0-5.el8.noarch is already installed.
Error:
Problem: libblkid-2.32.1-17.el8.i686 has inferior architecture
- package libblkid-devel-2.32.1-17.el8.x86_64 requires …
```
=> agent/rhel8: temporarily disable CodeReady repo

vagrant/boxes/Vagrantfile_archlinux_systemd
Version 2.35 contains a double-free issue which was already fixed in the
latest master[0]. Let's temporarily downgrade *util-linux to 2.34 until
the fixed version is released to Arch repositories.
See: https://github.com/systemd/systemd/pull/14677#issuecomment-579200696
[0] https://github.com/karelzak/util-linux/commit/caa37b6e18fdcd29e57ab82fe1d54b293fccbf3b
=> vagrant: pin util-linux & libutil-linux to 2.34

vagrant/vagrant-test-sanitizers.sh
Let's slightly extend the number of integration tests (`TEST-??-*`) we run under sanitizers to cover some of the larger systemd subcomponents introduced recently:
1) `TEST-04-JOURNAL` to cover `systemd-journald`
2) `TEST-45-REPART` to cover `systemd-repart` 
3) `TEST-46-HOMED` to cover `systemd-homed` and related stuff
~~`TEST-45-REPART` needs a small tweak to work correctly under sanitizers because the used `grep` statements were tripping over LSan which then killed `grep` during post-processing. Simple `LD_PRELOAD=` in front of each `grep` does the trick.~~ Fixed by systemd/systemd#14715
Also, I finally disabled `test-execute/exec-specifier-interpolation` as the completely random LSan crashes were driving me insane and I couldn't reproduce them on both Arch Linux and Fedora Rawhide …
=> vagrant: run certain other integration tests under sanitizers

vagrant/boxes/Vagrantfile_archlinux_systemd
A new version of util-linux ([2.35.1](https://github.com/karelzak/util-linux/releases/tag/v2.35.1)) has been released which should address the double-free issue. ~~Let's check that before reverting #215 (and thus fixing #216).~~ Seems to work as expected, let's revert the workaround.
=> vagrant: unpin util-linux

vagrant/boxes/Vagrantfile_archlinux_systemd
This reverts commit 0397444f18634fff38a0bbe6f0c54840208feec8.
Fixes: #208
Fixed by: systemd/systemd#14768
=> Revert "vagrant: temporarily pin libcap to v2.28"

agent/bootstrap.sh, agent/testsuite.sh
The host initrd contains the multipath module along with necessary
services, which are not used in the integration test suite and
occasionally cause unexpected failures.
Fixes: #222
=> agent: drop the multipath module from testsuite's initrd

jenkins/runners/systemd-cron-build.sh, jenkins/runners/systemd-pr-build-vagrant-sanitizers.sh, vagrant/bootstrap_scripts/arch-sanitizers-clang.sh
Passing `-Og` using `--optimization=g` doesn't work in combination with
clang, so let's do it this way, until it's fixed.
Also, this masks another issue, where systemd fails to build with `-O0`,
which should be dealt with later.
See:
- mesonbuild/meson#6619
- systemd/systemd#14865
=> vagrant: "fix" the clang build and use it as a default for PR testing

vagrant/vagrant-setup.sh
Beef up the nfsd check once again, as the race during Vagrant startup is
still there even though the nfsd seems to be running fine:
```
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```
=> vagrant: check and possibly load the  nfs & nfsd kernel modules

vagrant/bootstrap_scripts/arch.sh, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
The default mkinitcpio config includes only the udev module, which is
not enough and breaks certain scenarios. Replace the udev module with
the full-fledged systemd one to mitigate this.
Fixes: https://github.com/systemd/systemd/pull/14338#discussion_r397824601
See: https://wiki.archlinux.org/index.php/Mkinitcpio#Common_hooks
=> vagrant: include the systemd module in initrd

vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh, vagrant/bootstrap_scripts/arch.sh, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
The NFS volume we mount into the Vagrant VM with the systemd repository
has been giving me a headache for the past several months. Basically,
some of the Vagrant jobs (~5% of them) die due to the following issue:
```
/usr/bin/ld: error: /build/build/src/udev/libudev.so.1: file too short
collect2: error: ld returned 1 exit status
```
Apparently, this has to do something with desynchronized file timestamps
between the host and the guest, but even after installing and
configuring an NTP server on both sides the issue never went completely
away (see #201).
Let's just do the heavy lifting (compilation) on the internal VM storage
and see how it fares.
Fixes: #199
=> vagrant: move compilation away from NFS

vagrant/boxes/Vagrantfile_archlinux_systemd
See: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=3734fe98a51ca7e776052cdabc80be9885b7d40d
=> vagrant: wireguard is now part of the default kernel package

agent/testsuite.sh, vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
systemd/systemd#15281 introduces a change which collects all journals of
each integration tests and merges them into one located under
`$TESTDIR/system.journal`. Let's update the paths in CI scripts
accordingly.
---
I'll test this properly once systemd/systemd#15281 is merged.
=> agent/vagrant: tweak the journal location

common/task-control.sh, common/utils.sh
When running `coredumpctl debug` on journal files got from the
integration tests (particularly QEMU ones), we get useless results if
the build is not installed locally (i.e. without running `ninja
install`), 
as coredumpctl pulls in "incorrect" binaries - e.g
coredumpctl pulls in `/usr/bin/systemctl` it got from the
`COREDUMP_FILENAME=` journal field, but that file is different from the
one in the $BUILD_DIR, resulting usually in a useless trace.
Let's fix this by attempting to locate the binary from the
`COREDUMP_FILENAME=` field in the local $BUILD_DIR (if set) and if we
succeed, override the gdb command to load the just located binary before
running `bt full`.
Fixes: #237
=> common: fix getting gdb traces when the build is not installed locally

agent/testsuite-rhel7.sh, agent/testsuite-rhel8.sh, agent/testsuite.sh, common/utils.sh, vagrant/vagrant-test.sh
Checking for elements in array using the regex "solution" is quite ugly
and shellcheck doesn't like it at all. Let's introduce a new helper
which should make it easier & prettier
Also, skip the coredump check on TEST-48-UDEV-EVENT-TIMEOUT,
as it intentionally generates a few coredumps we're not interested in.
=> common: introduce `in_set` helper function

jenkins/runners/systemd-cron-build.sh, vagrant/vagrant-test-sanitizers.sh
Since dfe84a2d86b29eee95a38de416c43efc6ade8eb5 the LLVM/clang job has been disabled completely, as [BZ#1827338](https://bugzilla.redhat.com/show_bug.cgi?id=1827338) breaks `TEST-46-HOMED` (and possibly other things) under ASan.
Until it's fixed let's disable the problematic test so we can *salvage* the rest of the run and use it at least in the Jenkins cron job, since it sometimes discovers issues which gcc misses.
=> vagrant: work around the LLVM ASan issue & switch the cron job to clang

vagrant/boxes/Vagrantfile_archlinux_systemd
Kernels 5.6.8+ seem to have a bug in loopdev handling, which completely
breaks the integration test suite.
See: https://github.com/systemd/systemd/pull/15682
=> vagrant: pin Arch repos to 2020-04-29 to stick with kernel 5.6.7

jenkins/runners/systemd-cron-build.sh, jenkins/runners/systemd-pr-build-vagrant-sanitizers.sh, vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh, vagrant/vagrant-test-sanitizers.sh
Since version 10, both gcc and clang started to ignore certain linker errors
when compiling with -fsanitize=address. This eventually leads up to -lcrypt
not being correctly propagated, but the fact is masked by the aforementioned
issue. However, when the binary attempts to load a symbol from the libcrypt
binary, it crashes since it's not linked correctly against it.
Negating the -Wl,--as-needed used by default by -Wl,--no-as-needed seems to
help in this case.
See:
https://bugzilla.redhat.com/show_bug.cgi?id=1827338#c3
https://github.com/systemd/systemd-centos-ci/issues/247
/cc @evverx - this whole situation feels especially icky, hopefully I'm not missing something obvious :-)
=> vagrant: use LDFLAGS="-Wl,--no-as-needed" in sanitizer runs

agent-control.py, agent/bootstrap-rhel7.sh, agent/bootstrap-rhel8.sh, agent/testsuite-rhel8.sh, common/utils.sh, jenkins/runners/systemd-rhel8-pr-build.sh
Since RHEL 8.2 we kind of support the unified cgroup hierarchy (cgroups
v2) in addition to the legacy cgroups, so let's test both of them in
each RHEL 8 PR.
=> agent/rhel8: support testing on both legacy & unified cgroups

vagrant/vagrant-test.sh
After re-enabling the parallelization the number of test flakes
significantly rose and one of them pointed out a potential issue:
```
[ 1120.342877] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-nspawn:615]
[ 1148.342912] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-nspawn:615]
[ 1176.342872] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-nspawn:615]
qemu-system-x86_64: terminating on signal 15 from pid 105682 (timeout)
```
Let's halve the number of parallel tasks to see if the situation improves.
=> vagrant: halve the number of concurrent tasks

agent/bootstrap-rhel8.sh, agent/testsuite-rhel8.sh
Already done in the upstream job, but the issue is present in the RHEL 8
one as well.
See:
* 554d394d23139fa24fd10ac0c0370d46a4ac70d7
* d0f178328b7ef66868377c99f382969e2a4d9a84
---
Should fix the CI issue stumbled upon in https://github.com/systemd-rhel/rhel-8/pull/103.
=> agent/rhel8: drop the multipath module from testsuite's initrd

vagrant/vagrant-setup.sh
Yet another attempt to mitigate the still-present NFS issue:
```
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```
when starting VM. The rationale is that NFS server has a 90s grace
period (by default) after start during which it refuses any client
connections. Let's drop it to 5s, since we're in charge of all NFS
clients in this case, and wait for the grace period to pass, so we can
be sure the NFS server is indeed ready before trying to bring up a VM.
=> vagrant: configure the NFS grace period

agent/bootstrap.sh
This is a followup to c887e91ec60cbf686a74583ab73f98acccce595a.
Unfortunately, if the original time difference is too big, the mtime of
/etc/.updated is already too far in the future, so it doesn't matter if
we correct the time during the next boot, since it's still going to be
in the past. Let's just explicitly override all ConditionNeedsUpdate=
directives to true to fix this once and for all.
Example from the recent fail:
Current date:         Wed 27 May 11:07:42 BST 2020
RTC:                  2020-05-27 11:07:41.871700+01:00
/usr mtime:           Wed 27 May 11:03:58 BST 2020
/etc/.updated mtime:  Wed 27 May 11:46:28 BST 2020
the /etc/.updated mtime is in the future after the time correction, so
the units with ConditionNeedsUpdate= will be skipped on the next boot in
any case, causing …
=> agent: explicitly override ConditionNeedsUpdate= to true

vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh
The udevadm -> systemd-udevd symlink is created in the install phase which
we don't execute in sanitizer runs, so let's create it manually where
we need it
See: https://github.com/systemd/systemd/pull/15918
=> vagrant: support udevadm/systemd-udevd merge efforts

vagrant/vagrant-build.sh, vagrant/vagrant-setup.sh
As 541d0b008bac788e75d9bdd37437294bcbb3ab2e didn't help (sigh), let's
add a few more useful debug checks and raise the log level of vagrant
during provisioning.
=> vagrant: add additional debug checks to track down the NFS issue

vagrant/vagrant-test.sh
This reverts commit 8779abe.
After some debugging I noticed that the issue is still present, even
when the number of concurrent jobs is halved. However, when trying to
get deeper, the issue completely disappeared and I failed to reproduce
it in more than 20 consecutive runs.
In lights of this let's drop the workaround, since it doesn't work, and
wait if the issue reappears to dig into it even further.
=> Revert "vagrant: halve the number of concurrent tasks"

agent/bootstrap.sh, vagrant/boxes/Vagrantfile_archlinux_systemd
Namely:
* squashfs-tools for mksquashfs (Arch/CentOS 7)
* veritysetup for veritysetup (CentOS 7, on Arch the binary is part
of the cryptsetup package)
=> agent/vagrant: add new test dependencies for systemd/systemd#16046

common/task-control.sh, vagrant/vagrant-build.sh
Treating HT cores as "real" cores causes CPU over-saturation related
issues and random test fails. Since this happens only on "dusty" machines
(*.dusty.ci.centos.org), let's explicitly exclude HT cores there from the
total number of cores when creating a VM.
Hopefully addresses #270.
=> vagrant: avoid using HT cores on "dusty" CentOS CI machines

jenkins/runners/systemd-centos-ci-vagrant-make-cache.sh, utils/artifacts-copy-file.sh, vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/vagrant-build.sh, vagrant/vagrant-make-cache.sh, vagrant/vagrant-test.sh, vagrant/vagrantfiles/Vagrantfile_arch
So far we updated the Vagrant image every couple of days, gave it a
quick boot test to see if it's bootable, and then pushed it directly
into production. However, time has shown that this is actually not the
smartest idea, because there can be some interface changes or even bugs
introduced in some of the updated images, which completely breaks CI for
a while.
To avoid such scenarios, let's suffix the updated image with '-new', run
it through our usual pipelines, and if it succeeds drop the
'-new' suffix so the standard pipeline can use it without worrying it
may not work.
TBD: the renaming part, documentation
=> vagrant: test the updated image before using it in production

agent/testsuite.sh, vagrant/vagrant-test.sh
After the test suite rewrite we do a test pre-initialization via
initialize_integration_tests() helper, so we shouldn't clean up the just
initialized $TESTDIR anymore.
=> agent/vagrant: don't remove the pre-initialized $TESTDIR

common/task-control.sh
I noticed a rising amount of flakes since the introduction of
parallelization, many of them showing signs of CPU or I/O
starvation/overload. Let's halve the overall parallelization workload in
an attempt to trade off some overall speed for stability.
=> common: halve the parallelization workload

agent/bootstrap.sh
The corrected time & date doesn't persist across reboots, which means
that the machine will use the borked RTC time on the next boot. In that
case chrony attempts to fix it, but sometimes it does it too late in the
test phase. When this happens after some of the test images were
generated, they contain files with timestamps from the future, which
confuses the systemd unit cache after the time gets corrected, leading
to many unexpected (and bogus) fails because of missing unit files.
Related: https://github.com/systemd/systemd-centos-ci/issues/251#issuecomment-648180867
=> agent: reuse the corrected time & date after reboot

vagrant/vagrant-test-sanitizers.sh, vagrant/vagrant-test.sh
Since kernel 5.7.2 the macsec module is broken, causing a runtime NULL pointer
dereference (and since 5.8.0 an additional oops). Since the issue hasn't been
looked at/fixed for over a month now, let's disable the failing test to
no longer block the CI image updates.
See: systemd/systemd#16199
=> vagrant: temporarily disable test_macsec

common/utils.sh, vagrant/vagrant-test-sanitizers.sh
Otherwise we won't be able to look for possible sanitizer issues or
coredumps due to unsupported journal format.
=> vagrant: use the built journalctl/coredumpctl binaries when necessary

vagrant/boxes/Vagrantfile_archlinux_systemd
Since kernel 5.8.1 the test VMs started to randomly softlock when trying
to online non-boot CPUs. To make the CI stable again, let's revert back
to kernel 5.7.12.
See: https://bugs.archlinux.org/task/67649
=> vagrant: pin repositories to kernel 5.7.12 (2020-08-14)

agent/bootstrap.sh
systemd/systemd#13842 bumps the minimal meson version to 0.52.1 which is
no longer available in the CentOS 7 repositories
=> agent: bump meson to 0.52.1 on CentOS 7

vagrant/vagrant-test-sanitizers.sh
Reverts 6d7d22af5df1a8bca412ecc9d08628b42e8d0e4c
=> vagrant: drop the ASan wrapper for test-execute

vagrant/test_scripts/test-arch.sh
This reverts commit 983748e1ceb8a99855d880b3b0a3104ea0f64fe0.
=> Revert "vagrant: temporarily disable TEST-56-OOMD"

vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
otherwise it remains set for following tests, causing unintended skips
of the respective QEMU parts.
Follow-up to d9cdbb9 and
48b8517.
=> vagrant: unset the $TEST_NO_QEMU variable in each iteration

vagrant/vagrant-setup.sh
Unfortunately, RHEL 8.3's libssh suffers from the same issue as
krb5-libs, thus requiring us to rebuild it against bundled OpenSSL.
=> vagrant: recompile libssh in addition to krb5

agent/testsuite.sh, vagrant/test_scripts/test-arch.sh
Since the issue has started appearing in the CentOS 7 runs as well,
let's tweak the existing workaround and extend it to both runs to make
the CI stable again, until a proper solution (with journal valiadation)
is implemented.
See: systemd/systemd#17963
Follow-up to a632f4f596530fbee7a71644cd98e5ba394fc21a.
=> agent/vagrant: skip test-journal-flush in TEST-02-UNITTESTS

agent/testsuite.sh, vagrant/test_scripts/test-arch.sh
The actual workaround, because dumb me didn't realize the integration
tests use ninja/meson to install the build into a custom rootfs, thus
rebuilding the missing files, sigh.
Follow-up to 93829fcb5348ce5cb5f097d987f32a094ffaeb25.
=> agent/vagrant: skip test-journal-flush in TEST-02-UNITTESTS #2

agent/testsuite.sh, vagrant/test_scripts/test-arch.sh
Move the recently introduced workarounds before the `meson test`
execution, otherwise the setup scripts of the integration tests will
trigger a partial ninja rebuild due to changed files, and because they
run in parallel bad things follow, like:
```
D: Install compiled systemd
+ DESTDIR=/var/tmp/systemd-test-TEST-01-BASIC/root
+ /sbin/ninja -C /systemd-meson-build install
ninja: Entering directory `/systemd-meson-build'
...
20/452] Generating systemd-bootx64.efi with a custom command
FAILED: src/boot/efi/systemd-bootx64.efi
/usr/bin/objcopy -j .text -j .sdata -j .data -j .dynamic -j .dynsym -j '.rel*' --target=efi-app-x86_64 src/boot/efi/systemd_boot.so src/boot/efi/systemd-bootx64.efi
/usr/bin/objcopy: error: the input file 'src/boot/efi/systemd_boot.so' is empty
```
and many more...
=> agent/vagrant: reorder workarounds

agent/testsuite.sh, vagrant/test_scripts/test-arch.sh
Since systemd/systemd@d9e606e each test use a base image which they
build on. However, with the current parallel test setup this introduces
a race condition, where each test tries to create the base image.
Let's initialize the base image separately and then run the rest of the
tests along with their setup phases.
=> Tweak the image initialization

agent/testsuite.sh, common/task-control.sh, vagrant/test_scripts/test-arch.sh
This is a somewhat ugly solution to keep journals of all task retries
instead of just the last one.
=> common: collect & check all journals generated by exectask_retry()

vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh
Apparently, mixing CFLAGS/CXXFLAGS/LDFLAGS and their meson counterparts
is unsupported, so let's convert the existing flags to meson's
equivalents to keep the builds happy.
=> vagrant: 'mesonize' the compiler flags

agent/testsuite.sh, common/utils.sh, vagrant/test_scripts/test-arch.sh
This test was recently merged with other udev-related tests. However,
since one of them triggers a couple of coredumps, the coredumpctl_*
stuff was disabled for this particular test.
To ensure we don't miss any legit systemd-udevd coredumps, let's enable
the coredump checks, but explicitly exclude expected coredumps for certain
binaries using the recently introduced $COREDUMPCTL_EXCLUDE_RX variable.
=> tree-wide: check for coredumps in TEST-17-UDEV 

common/task-control.sh, common/utils.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh
If we end up loading symbols from a different binary (like in the sanitizer
runs), dump the stack trace of all threads to simulate the original
`coredumpctl info` format (which is in these cases useless, as it is
symbolized with a different binary).
=> common: dump the stack trace of all threads after reloading symbols

agent/bootstrap.sh, vagrant/bootstrap_scripts/arch-sanitizers-clang.sh, vagrant/bootstrap_scripts/arch-sanitizers-gcc.sh, vagrant/boxes/Vagrantfile_archlinux_systemd
After a bit of manual testing it looks like all tests currently tagged
as 'slow' are capable of running under sanitizers without timeouts.
=> vagrant: let's run even slow tests under sanitizers

agent/bootstrap.sh, agent/testsuite.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh, vagrant/vagrant-build.sh, vagrant/vagrantfiles/Vagrantfile_arch, vagrant/vagrantfiles/Vagrantfile_rawhide
This should allow us run tests which require $XDG_RUNTIME_DIR and/or
$DBUS_SESSION_BUS_ADDRESS to be set correctly, since `sudo` nor `su`
does that.
=> vagrant: use 'root' as the default user for `vagrant ssh`

agent/bootstrap-rhel8.sh, agent/testsuite-rhel8.sh
netcat is now provided by two packages (nmap-ncat from AppStream and
netcat from EPEL), but TEST-13 works only with nmap-ncat. Let's make
sure we use the correct version.
Also, move the dep installation into the bootstrap script to keep it in
one place.
=> agent: use the "correct" netcat version on CentOS 8

agent/bootstrap-rhel8.sh, agent/bootstrap.sh
In several cases (one pretty recent) systemd crashed during
daemon-reexec done before reboot and the reboot never happened. To catch
this scenario as well, try to collect any possible coredumps before
rebooting the machine, so we have at least something actionable if it
hapens.
=> agent: collect coredumps before reboot as well

common/utils.sh
PR systemd/systemd#19336 was updated and now it's
/usr/bin/sleep which gets a sigabort:
```
13:29:04 [coredumpctl_collect] Excluding coredumps matching '/(test-execute|dhcpcd|bin/python3.[0-9]+|platform-python3.[0-9]+|bash)$'
13:29:04 [coredumpctl_collect] Gathering coredumps for '/usr/bin/sleep'
13:29:04            PID: 165086 (sleep)
13:29:04            UID: 0 (root)
13:29:04            GID: 0 (root)
13:29:04         Signal: 6 (ABRT)
13:29:04      Timestamp: Mon 2021-04-19 13:40:31 CEST (48min ago)
13:29:04   Command Line: sleep 5
13:29:04     Executable: /usr/bin/sleep
13:29:04  Control Group: /machine.slice/TEST-57-RELOADING-RESTART.scope/payload/system.slice/testservice-abort-restart-57.service
13:29:04           Unit: TEST-57-RELOADING-RESTART.scope
13:29:04          Slice: …
```
=> common: ignore sleep instead of bash coredumps

vagrant/test_scripts/test-arch-sanitizers-clang.sh
Some of the tests are even more flaky under sanitizers, so let's make
sure we don't disrupt the results with annoying false-positives.
=> vagrant: use the default # of retries (3) under sanitizers as well

agent/bootstrap.sh, utils/reposync.sh
yum/reposync on CentOS 7 doesn't support --forcearch/--norepopath and
also has issues with syncing multiarch repositories. Let's use
a monkey-patched dnf instead to make this work for now, until the Jenkins
workers are upgraded to CentOS 8.
=> common: support multiple repositories/arches during reposync

agent/testsuite.sh
Basically the same stuff & reasoning as in
8003bcee22890981e0cf13ee37cc5675403a4863.
=> agent: avoid using HT cores for meson on dusty machines

agent/bootstrap.sh
Also, drop a forgotten leftover workaround to enable homed on CentOS 8.
=> agent: install bpftool & clang for -Dbpf-framework

agent/bootstrap-rhel8.sh, agent/bootstrap-rhel9.sh, agent/testsuite-rhel8.sh, agent/testsuite-rhel9.sh, jenkins/runners/rhel9-centos9.sh
Since there's no RHEL 9 public compose yet, we'll have to run the tests
on CentOS 8.
=> agent: add CI scripts for RHEL 9

agent/bootstrap.sh, vagrant/boxes/Vagrantfile_archlinux_systemd
@mrc0mmand is this enough to install the libbpf package in the image too? Context: https://github.com/systemd/systemd/pull/19705
=> agent/vagrant: install libbpf from repository instead of manual build

vagrant/boxes/Vagrantfile_archlinux_systemd
This reverts commit 0d14bdfe9a627bf496294edeffdb4c097c306439.
Fixes: #388
=> Revert "vagrant: temporarily skip libcap pkg upgrade"

agent/testsuite-rhel8.sh
Essentially the same scenario as in 93829fc and 76a69b4, but for
RHEL/CentOS 8 job.
=> agent/rhel8: skip test-journal-flush under QEMU

vagrant/vagrant-make-cache.sh
Since F34 Fedora uses btrfs as the default FS, which causes errors[0]
when re-boxing such image, since CentOS 8 doesn't understand btrfs.
Let's workaround this by using a couple of custom packages, which
were rebuilt to make them "btrfs-aware".
[0]
```
==> rawhide_selinux: Packaging domain...
==> rawhide_selinux: Downloading vagrant-cache-MzSmg_rawhide_selinux.img to /root/vagrant-cache-MzSmg/_tmp_package/box.img
==> rawhide_selinux: Image has backing image, copying image and rebasing ...
virt-sysprep: error: libguestfs error: inspect_os: mount exited with status
32: mount: /tmp/btrfs0jA5db: unknown filesystem type 'btrfs'.
```
=> vagrant: use btrfs-aware packages to tweak Fedora images

vagrant/test_scripts/test-arch-sanitizers-clang.sh
The test keeps randomly failing due to spurious timeouts caused by CPU
soft lockups. Since this happens only with this specific test (and also
only under sanitizers), disable nested KVM just for it.
```
[  252.675662] kernel: watchdog: BUG: soft lockup - CPU#3 stuck for 27s! [systemd:1]
[  252.678963] kernel: Modules linked in: ext4 crc32c_generic crc16 mbcache jbd2 sr_mod cdrom ata_generic pata_acpi serio_raw atkbd libps2 ata_piix floppy crc32c_intel i8042 serio
[  252.678963] kernel: CPU: 3 PID: 1 Comm: systemd Not tainted 5.12.14-arch1-1 #1
[  252.678963] kernel: Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS ArchLinux 1.14.0-1 04/01/2014
[  252.678963] kernel: RIP: 0010:__do_softirq+0x79/0x2c1
[  252.678963] kernel: Code: 81 67 2c ff f7 ff ff be 00 01 00 00 e8 c0 f5 2c ff …
```
=> vagrant: disable nested KVM for TEST-13-NSPAWN-SMOKE w/ sanitizers

vagrant/bootstrap_scripts/rawhide-selinux.sh
to allow building with OpenSSL 3.x.
See: https://github.com/systemd/systemd/issues/20775
=> vagrant: temporarily disable the deprecated-declarations check

vagrant/boxes/Vagrantfile_archlinux_systemd
Unfortunately, this package is not available in Arch repositories (only
AUR), so let's build it ourselves.
=> vagrant: compile & install tgt (iSCSI target utils)

vagrant/bootstrap_scripts/rawhide-selinux.sh
This reverts commit 9c76fc7dff4c2b68e6df20299d05a9fec6acf62e.
Fixed by https://github.com/systemd/systemd/pull/20876
=> Revert "vagrant: temporarily disable the deprecated-declarations check"

utils/reposync.sh
As of 2021-09-30 one of the Let's Encrypt's root certificates expired,
which in combination with CentOS 7's OpenSSL causes verification fails
in tools using OpenSSL (like wget). Let's use curl instead, which uses
NSS that doesn't suffer from this issue.
Another option is to upgrade the `ca-certificates` package, but since we
don't have root in the OCP container, this is not possible.
See:
* https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
* https://access.redhat.com/articles/6338021
=> utils: use curl instead of wget

utils/reposync.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh
Follow-up to 475025c11b40c15a80ec7534d26f32022b3003c3.
=> tree-wide: use lowercase for local variables

agent/bootstrap.sh
See: https://sigs.centos.org/kmods/
=> agent: use the Kmods SIG repository to install wireguard on C8

vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
`test_exec_ioschedulingclass.exec-ioschedulingclass-none.service` from
`test-execute` keeps failing since kernel 5.15 due to a change in the
kernel API. Until the issue is resolved (on either side), let's skip the
test to not disturb the CI.
See: systemd/systemd#21087
=> vagrant: temporarily disable one of the test-execute's subtests

vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
This reverts commit bb79a5d4b3efb4b6fca18d0c4501a3154c12db0e.
See: systemd/systemd#21503
=> Revert "vagrant: temporarily disable one of the test-execute's subtests"

agent/testsuite.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch.sh
The flakiness should be, hopefully, fixed by systemd/systemd#21529.
=> agent/vagrant: re-enable test-journal-flush

agent-control.py, agent/bootstrap-rhel8.sh
Should, hopefully, fix the CI fail in https://github.com/redhat-plumbers/systemd-rhel8/pull/213.
=> agent: reexec the user daemon as well (RHEL 8)

vagrant/bootstrap_scripts/rawhide-selinux.sh
to allow building with OpenSSL 3.x (again).
See: https://github.com/systemd/systemd/pull/21170#issuecomment-985505461
=> vagrant(selinux): temporarily disable the deprecated-declarations check

agent/bootstrap.sh, vagrant/boxes/Vagrantfile_archlinux_systemd
=> tree-wide: install `screen` required by TEST-69-SHUTDOWN

vagrant/boxes/Vagrantfile_archlinux_systemd
See: systemd/systemd#21838
Follow-up to ec8068b4054c6af737d9f2e470058c18237b1a41.
=> vagrant(arch): install `python-pexpect` required by TEST-69-SHUTDOWN

agent/bootstrap.sh, vagrant/bootstrap_scripts/rawhide-selinux.sh, vagrant/vagrant-setup.sh
introduced in de2aa4b713f95fea2e133f8cfd9e18906fec3f14.
=> tree-wide: use the new repo mirror path

agent/testsuite-rhel9.sh
This reverts commit e58bb66.
Fixed by https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/177.
=> Revert "agent: disable test-watchdog on C9S"

vagrant/boxes/Vagrantfile_archlinux_systemd
to catch (or at least attempt to) some systemd-logind related issues.
=> vagrant(arch): install & start GDM by default

vagrant/boxes/Vagrantfile_archlinux_systemd
Follow-up to 7bfc86e3cc8e93b5d950541afe82e267e20a6602.
=> vagrant(arch): explicitly set the default target to graphical.target

common/utils.sh
Sometimes we hit a point where some repositories have desynchronized
packages/metadata, causing intermittent fails. Let's bump the number of
retries and make the delay between each reply multiplicative to give the
mirrors a bit more time to sync properly without compromising CI
reliability.
=> common: make the cmd_retry()'s delay multiplicative

vagrant/bootstrap_scripts/arch-coverage.sh, vagrant/test_scripts/test-arch-coverage.sh
to account for newly created directories by gcov.
(This could be done with sticky bits as well, but using ACLs feels more
readable.)
=> vagrant(coverage): set the default ACL for the build dir

agent/bootstrap.sh
Get the build dependencies from a systemd specfile instead of using the source
repositories, since they're ATTOW under a heavy load
See: https://pagure.io/centos-infra/issue/680
=> agent: get systemd build deps from the systemd's specfile

agent/bootstrap.sh
This reverts commit 1734a4b082c49409324acd54d973936b8a128a53.
vault.centos.org has been moved behind a Cloudfront cache, so this
workaround should no longer be necessary.
See: https://pagure.io/centos-infra/issue/682
=> Revert "agent: get systemd build deps from the systemd's specfile"

agent-control.py, agent/bootstrap-rhel9.sh, agent/testsuite-rhel9-sanitizers.sh, jenkins/runners/rhel9-centos9-sanitizers.sh
Since in RHEL 9/C9S we finally have a reasonably up-to-date codebase to
pull this off, let's run certain tests with ASan & UBsan to check for
possible memory leaks and other nasty issues.
=> agent(rhel9): introduce the sanitized job

common/task-control.sh
All dusty machines have Intel Xeon CPUs with 4 cores and HT enabled,
which causes issues when the HT cores are counted as "real" ones, namely
CPU over-saturation and strange hangups. As all dusty server have the
same HW, let's manually override the # of CPUs for the VM to 4.
Even though this will make the jobs running on the affected machines
slower it should make them more reliable, which outweighs the runtime
penalty.
Resolves: #477
Follow-up to: 8003bcee22890981e0cf13ee37cc5675403a4863
=> common: override the # of CPUs and queue size on *.dusty machines

vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/boxes/Vagrantfile_rawhide_selinux
since we don't use it anyway and it causes weird issues with the recent
Rawhide boxes.
=> vagrant: disable the default /vagrant rsync'ed folder

agent/testsuite.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
Thanks to https://github.com/systemd/systemd/pull/22992 many of such tests should be now stable.
=> tree-wide: significantly reduce the amount tests marked as 'flaky'

vagrant/boxes/Vagrantfile_archlinux_systemd
Revert once https://bugs.archlinux.org/task/74716 is resolved.
=> vagrant(arch): downgrade QEMU to 6.2.0

agent/testsuite-rhel7.sh, agent/testsuite-rhel8.sh, agent/testsuite-rhel9-sanitizers.sh, agent/testsuite-rhel9.sh, agent/testsuite.sh, common/task-control.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh, vagrant/test_scripts/test-rawhide-selinux.sh
to reduce code duplication. Also, set the exit code explicitly, since in
the future we might run more than 255 tasks which would overflow the
uint16 value for exit, causing unexpected passes (e.g. 256 fails == exit
code 0).
=> tree-wide: move summary into a separate function

vagrant/boxes/Vagrantfile_archlinux_systemd
This reverts commit bf3ccd9e95f47339cbbacd2833cbbbd11c1f75bd.
Resolves: #488
=> Revert "vagrant(arch): downgrade QEMU to 6.2.0"

vagrant/boxes/Vagrantfile_archlinux_systemd
which are required for the NFS share to work correctly.
=> vagrant: install nfs-utils & ntp

agent/bootstrap-alt.sh, agent/testsuite-alt.sh
Let's try to run tests on a sanitized build on newly supported alternative architectures.
TBD
---
[2020-12-09] There's no QEMU package for the ppc64le arch, and we can't run KVM there, since the machines are already virtualized, so the support for integration tests is not possible for now
=> Support alternative architectures (ppc64le & aarch64)

agent/testsuite-alt.sh
since the alt-arch nodes in CentOS CI don't support nested KVM (yet).
=> agent(upstream): use standard QEMU on ppc64le nodes

agent/testsuite-alt.sh, agent/testsuite-rhel8.sh, agent/testsuite-rhel9-sanitizers.sh, agent/testsuite-rhel9.sh, agent/testsuite.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
meson also generates xml and json files which we don't need for possible
debugging. Omitting these files saves ~16M per job.
=> tree-wide: save only meson's text artifacts

agent/bootstrap-alt.sh
Since we're not rebooting the machine in the alt-arch runs, install
kernel-tools and other kernel packages for the currently running kernel
instead of the latest one.
=> agent(upstream-alt): install specific kernel-tools version

agent/bootstrap-alt.sh
to make the systemd-networkd test suite happy.
Since we don't install the built revision, let's install the timesync
package as well, which provides the necessary units, users, and other
configuration.
=> agent(alt): install systemd-timesync

agent-control.py
Because the cloud-init.target doesn't exist in the user scope, hence the
dependency requirement is a no-op.
=> agent-control: don't use a user session for the transient unit

common/task-control.sh
This should speed up especially the coredump/sanitizer checks, as they
take < 1s and we run dozens of them in a sequence.
=> common: shorten the sleep before checking a process

agent/testsuite.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
Let's gather possibly useful information about CPU soft lockups
occasionally triggered by TEST-13-NSPAWN-SMOKE. Since they happen even
without nested KVM, enable nested KVM unconditionally, but trigger a
kernel panic on CPU soft lockups, which should dump more information
about it, and follow it by reboot-on-panic logic to not waste CI time in
a stuck test.
=> vagrant(arch): get more info about soft lockups if/when they happen

utils/artifacts-copy-file.sh, vagrant/vagrant-make-cache.sh, vagrant/vagrantfiles/Vagrantfile_arch, vagrant/vagrantfiles/Vagrantfile_rawhide
The legacy artifact box migration is complete, so let's use the old
artifact box URL again, which also has a valid TLS cert.
=> tree-wide: s/artifacts.ci.aws.centos.org/artifacts.ci.centos.org/g

agent/testsuite.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
This reverts commit dba929fdc2781fe98d4fce10c94d051d6fca4770.
=> Revert "vagrant(upstream): temporarily skip TEST-29 under sanitizers"

agent/testsuite.sh
Let's see if systemd/systemd#17078 is still relevant.
Reverts: ea95b482
=> agent(upstream): reenable test-seccomp

.github/workflows/differential-shellcheck.yml, vagrant/vagrant-setup.sh
This should help with intermittent `vagrant plugin install` errors:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a
configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:
timed out (https://rubygems.org/specs.4.8.gz)
Source: https://rubygems.org/
```
=> vagrant: make the setup stuff a bit more robust

agent/testsuite.sh
Let's attempt to run TEST-64 as early as possible, since it's current runtime (~48m) wastes the resources, as it runs as one of the last tests.
=> agent(upstream): re-shuffle the test list

vagrant/test_scripts/test-arch-sanitizers-clang.sh
With the latest tweaks it appears to be stable under ASan and the runtime seems to be reasonable as well:
OK (2m)   testcase_megasas2_basic()
OK (45s)  testcase_nvme_basic()
OK (45s)  testcase_virtio_scsi_identically_named_partitions()
OK (2m)   testcase_multipath_basic_failover()
OK (1m)   testcase_simultaneous_events()
OK (3m)   testcase_lvm_basic()
OK (2m)   testcase_btrfs_basic()
OK (2m)   testcase_iscsi_lvm()
OK (1m)   testcase_long_sysfs_path()
OK (2m)   testcase_mdadm_basic()
OK (1m)   testcase_mdadm_lvm()
=> vagrant(arch): run TEST-64-UDEV-STORAGE with sanitizers

agent/testsuite-rhel9-sanitizers.sh, agent/testsuite-rhel9.sh, agent/testsuite.sh, common/task-control.sh, vagrant/test_scripts/test-arch.sh, vagrant/vagrant-build.sh
since all jobs were migrated to AWS and the seamicro chassis are going to disappear soon.
=> tree-wide: drop all seamicro-related workarounds

agent/testsuite-alt.sh
Since with the recent test additions we've started hitting timeouts
again.
=> agent(alt): bump the meson test timeout even more

agent/testsuite-rhel8.sh, agent/testsuite.sh, common/task-control.sh
Otherwise they might accumulate from the retried tasks and cause
unexpected fails, as the storage on the EC2 machines is quite small.
=> agent(c8s): remove the test images unconditionally

agent/testsuite-alt.sh
As the machines are quite slow, running the networkd test suite in parallel with other integration tests causes spurious timeouts.
=> agent(alt): serialize the networkd testsuite on alt-archs

agent/testsuite.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch.sh
It's no longer necessary, as since systemd/systemd@10d7ed12c9 we configure the machine name directly in the test "framework".
=> tree-wide(upstream): drop the nspawn scope workaround

agent/testsuite-alt.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh
Introduced in systemd/systemd#25229.
=> tree-wide(upstream): run TEST-26-SYSTEMCTL with sanitizers

agent/testsuite-rhel9-sanitizers.sh
Introduced by rebase in RHEL 9.2 (v250 -> v252).
=> agent(rhel9+asan): run tests introduced in v252

agent/testsuite-rhel9-sanitizers.sh, agent/testsuite-rhel9.sh
As the issues should be resolved in systemd v252 we rebased to in RHEL 9.2.
=> agent(rhel9): limit the workarounds to RHEL < 9.2

agent-control.py, jenkins/runners/upstream-centos8.sh
Let's implement the timeout directly in agent-control, so we can collect as much artifacts as we can when a timeout occurs.
=> agent-control: allow setting a timeout for the job

agent/testsuite-rhel8.sh, agent/testsuite-rhel9.sh, agent/testsuite.sh, common/task-control.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
When retrying a task suffix the nspawn container name with the retry ID, so each retry has a unique name, otherwise we might end up with a scope name clash if the container was SIGKILLed (due to a timeout):
```
Spawning container TEST-69-SHUTDOWN on /var/tmp/systemd-test-TEST-69-SHUTDOWN_2/root.
Press Ctrl-] three times within 1s to kill container.
Failed to allocate scope: Unit TEST-69-SHUTDOWN.scope was already loaded or has a fragment file.
```
=> common: mangle nspawn container name as well if necessary

agent/bootstrap-alt.sh, agent/bootstrap.sh, vagrant/boxes/Vagrantfile_archlinux_systemd
Introduced in https://github.com/systemd/systemd/pull/26719.
=> upstream: install fsverity-related utils for TEST-29-PORTABLE

agent-control.py, requirements.txt
Extend the cloud-init/dnf workaround to also check for any potentially
running dnf processes to finish to avoid clashing with them:
```
2023-03-19 14:17:46,416 [agent-control/execute_local_command] INFO: Executing a LOCAL command: /usr/bin/ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=180 -o TCPKeepAlive=yes -o ServerAliveInterval=30 -l root n27-37-59.pool.ci.centos.org systemd-run --wait -p Wants=cloud-init.target -p After=cloud-init.target true && systemctl --user daemon-reexec
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'n27-37-59.pool.ci.centos.org,172.27.37.59' (ECDSA) to the list of known hosts.
Running as unit: run-u33.service
Finished with result: success
Main processes terminated with: …
```
=> agent-control: wait for any potential dnf processes to finish

agent-control.py
Sometimes when we get a fresh machine from the AWS pool we might hit
a transient network issue during the first ssh connection:
```
2023-03-25 13:13:44,522 [agent-control/allocate_node] INFO: Allocated node n27-44-182.pool.ci.centos.org with session id 173151
2023-03-25 13:13:44,523 [agent-control/main] INFO: Wait until the machine is fully initialized
2023-03-25 13:13:44,523 [agent-control/execute_remote_command] INFO: Executing a REMOTE command on node 'n27-44-182.pool.ci.centos.org': ...
2023-03-25 13:13:44,523 [agent-control/execute_local_command] INFO: Executing a LOCAL command: /usr/bin/ssh -t -o ...
Pseudo-terminal will not be allocated because stdin is not a terminal.
ssh: Could not resolve hostname n27-44-182.pool.ci.centos.org: Name or service not known
```
Let's do a test ssh …
=> agent-control: check if we can ssh after allocating a node

.github/workflows/differential-shellcheck.yml
Also, run the check on push events as well to suppress the "new shellcheck configuration" message.
=> ci: bump Differential Shellcheck to v4

agent/testsuite.sh, vagrant/test_scripts/test-arch.sh
Otherwise it has no effect in tests that use the base image.
Resolves: #614
=> Set $STRIP_BINARIES _before_ creating the base image

agent/bootstrap-rhel9.sh
Since kernel-5.14.0-295.el9 is currently FUBAR in AWS, see https://bugzilla.redhat.com/show_bug.cgi?id=2184745.
=> agent(rhel9): temporarily pin kernel to kernel-5.14.0-293.el9

vagrant/test_scripts/test-arch-sanitizers-clang.sh
[0] should be now resolved in both gcc and clang currently present on Arch.
[0] https://bugzilla.redhat.com/show_bug.cgi?id=2098125
=> vagrant: run TEST-35-LOGIN with sanitizers

agent-control.py, agent/testsuite.sh, jenkins/runners/upstream-centos8-stable.sh, jenkins/runners/upstream-centos8.sh
Since the issues with overloaded AWS regions are still there and are unlikely to disappear in a foreseeable future, let's give up on the QEMU stuff and run only tests that run in nspawn. We'll lose some coverage on C8S (mainly from TEST-64), but it's still better than not running anything.
To make up for this, I'll set up a cron job that'll run the whole test suite at least once a day in the "non-busy" hours.
=> agent: run only nspawn tests in the C8S job on PRs

agent/bootstrap-rhel8.sh, agent/bootstrap-rhel9.sh, agent/bootstrap.sh, vagrant/bootstrap_scripts/arch.sh
The debug logs are quite noisy and actually slow down the machine boot, as the console becomes oversaturated. Since we store the machine journal anyway let's forward logs to console only in initrd to have something actionable if something blows up during early boot.
=> Forward logs to console only in initrd during boot check

vagrant/boxes/Vagrantfile_archlinux_systemd
Until a new version with captive portal support is released.
=> vagrant: build & install latest radvd

vagrant/bootstrap_scripts/arch.sh, vagrant/boxes/Vagrantfile_archlinux_systemd, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh, vagrant/vagrant-make-cache.sh, vagrant/vagrantfiles/Vagrantfile_arch
Split out of #641, as the UEFI part needs more work.
=> vagrant: use the official Arch Linux image

agent/testsuite-rhel9.sh
To hopefully work around random early VM lockups I've seen in the RHEL 9 jobs.
=> agent(rhel9): use the Q35 chipset with (possibly) TCG

agent/bootstrap-rhel9.sh
Even though the kernel with necessary patches is present in C9S repos, the latest AMI used by CentOS CI is still on kernel-5.14.0-325. As we don't reboot the machine in the sanitizer job, let's temporarily revert the respective patches there to make the job happy again.
=> agent(rhel9): temporarily revert reverts for idmapped mounts

agent/bootstrap-rhel9.sh
This reverts commit 0406213a97e6e6fe5808734c269e0c12bab0f667.
The [RHBZ#2234390](https://bugzilla.redhat.com/show_bug.cgi?id=2234390) has been fixed in kernel-5.14.0-362.el9.
Resolves: #654
=> Revert "agent(rhel9): temporarily pin kernel to kernel-5.14.0-354.el9"

vagrant/vagrant-make-cache.sh
Since we use it in paths to kernel and initrd images on the ESP.
=> vagrant: don't truncate existing /etc/machine-id when packaging the box

vagrant/boxes/archlinux_systemd.sh, vagrant/vagrant-make-cache.sh
In order to test the FIDO2 stuff in systemd, let's make use of the
CanoKey QEMU module [0]. Apart from building & installing just the
canokey-qemu stuff [1], we unfortunately have to rebuild QEMU as well
to actually enable the CanoKey device.
[0] https://www.qemu.org/docs/master/system/devices/canokey.html
[1] https://github.com/canokeys/canokey-qemu
=> vagrant(arch): rebuild QEMU with CanoKey support

vagrant/boxes/archlinux_systemd.sh, vagrant/vagrant-make-cache.sh
Which seems to help with https://github.com/systemd/systemd-centos-ci/issues/660.
=> vagrant(arch): temporarily switch to an LTS kernel

vagrant/boxes/archlinux_systemd.sh
The original issue [0] got resolved far quicker than I originally anticipated, and the fixed package has already hit the stable repos, so let's revert the workaround as well.
[0] https://bugs.archlinux.org/task/79810
This reverts commit 9500181727a3074e60cef721b82083d022f69e09.
=> Revert "vagrant(arch): pin repos to 2023-09-24 with glibc 2.38-3"

vagrant/bootstrap_scripts/rawhide-selinux.sh
Until a patched version of dracut is released.
=> vagrant(rawhide): explicitly copy systemd-executor into the initrd

vagrant/boxes/archlinux_systemd.sh
To make the file has higher precedence over the default .network files.
For https://github.com/systemd/systemd/pull/29930.
=> vagrant(arch): prefix .network file with digits

agent/bootstrap.sh
This is also for https://github.com/systemd/systemd/pull/29930.
=> agent(upstream): also install .network file to make eth0 not managed by networkd

vagrant/bootstrap_scripts/arch.sh
Since the option is disabled by default, let's enable it in the Arch Linux job to make sure we don't break it in the future.
Resolves: #678
=> vagrant(arch): install default .network files in the Arch job

vagrant/boxes/archlinux_systemd.sh
The original issue [0] should be resolved/worked around by not forwarding the test logs through the slow serial console, but instead dumping them only once the test finishes, see [1].
[0] https://github.com/systemd/systemd-centos-ci/issues/660
[1] https://github.com/systemd/systemd/pull/30119
This reverts commit 3f6f8c8b3d19b24ec71f3bbc32dcfd63dde1023e.
Closes #659.
=> Revert "vagrant(arch): temporarily switch to an LTS kernel"

vagrant/boxes/archlinux_systemd.sh
Should be resolved by
https://gitlab.archlinux.org/archlinux/packaging/packages/multipath-tools/-/issues/1
This reverts commit f7088d25aa91122f0b195ade5b5591ed59c659c1.
=> Revert "vagrant(arch): temporarily pin multipath-tools to 0.9.6"

agent/bootstrap.sh
Latest C8S kernel panics on boot with unified cgroup hierarchy, see https://issues.redhat.com/browse/RHEL-17504
=> agent(upstream): pin kernel to kernel-4.18.0-521.el8

agent/bootstrap-alt.sh, agent/bootstrap-rhel8.sh, agent/bootstrap-rhel9.sh, agent/bootstrap.sh
The fixed kernel finally made it to mirrors, so let's drop all related workarounds.
This reverts commits:
- bb98bf5
- eee35be
- f9bffbd
- 1a13d28
Resolves: #687
=> Revert "agent: pin kernel to kernel-4.18.0-521.el8"

vagrant/test_scripts/test-arch-sanitizers-clang.sh
So we avoid trashing when running dfuzzer.
=> vagrant(arch): bump the test VM memory to 8G when running w/ ASan

agent/bootstrap-rhel9.sh
kernel-5.14.0-410.el9.x86_64 corrupts the XFS file system if used together with kexec, so let's temporarily downgrade to kernel-5.14.0-407.el9.x86_64.
See: https://issues.redhat.com/browse/RHEL-22465
=> agent(rhel9): pin kernel to kernel-5.14.0-407.el9.x86_64

vagrant/boxes/archlinux_systemd.sh
To get around [0] until a new official build is released.
[0] https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/20
=> vagrant(arch): install a fixed gcc build 

agent/bootstrap.sh
As EFI is not supported there, which makes the ukify test sad.
=> agent(upstream): don't build ukify on ppc64le

agent/testsuite-rhel8.sh, agent/testsuite-rhel9-sanitizers.sh, agent/testsuite-rhel9.sh, agent/testsuite.sh, common/utils.sh, vagrant/test_scripts/test-arch-coverage.sh, vagrant/test_scripts/test-arch-sanitizers-clang.sh, vagrant/test_scripts/test-arch.sh
gdb should do this automagically [0], so let's drop this (as the option
is apparently not in C9S's gdb even though it supports debuginfod just
fine).
[0] https://wiki.archlinux.org/title/Debuginfod
=> Revert "common: tell gdb to use debuginfod if available" 

vagrant/boxes/archlinux_systemd.sh, vagrant/vagrant-make-cache.sh
Provided by https://github.com/archlinuxhardened/selinux.
=> vagrant: install SELinux-aware tools from a binary repo

agent/bootstrap-rhel9.sh
RHEL-22465 has been resolved and a fixed kernel is already on the mirrors (5.14.0-412.el9.x86_64), so let's revert the kernel pin.
This reverts commit 63dbbd8b44b37557854d6faec8b0e8b9235f1450.
=> Revert "agent(rhel9): pin kernel to kernel-5.14.0-407.el9.x86_64"

vagrant/vagrant-make-cache.sh
Turns out fda0e4b was true only for the archlinux/archlinux box, so let's make the approach slightly more generic and use whatever Vagrantfile we can find under ~/.vagrant.d/boxes/<box_name>.
=> vagrant: make the search for the original Vagrantfile more generic

agent/bootstrap.sh
This reverts commit 55dc5fe062ca949fd139a8323a65f832b12ccef3.
=> Revert "agent(upstream): skip fuzz tests on ppc64le"

common/utils.sh
We don't care about submodules and it causes intermittent errors all over the place.
=> common: skip submodules when checking out the PR branch

common/utils.sh
The underlying issue [0] should be resolved, so let's see if that's indeed the case.
[0] https://gitlab.com/qemu-project/qemu/-/issues/2220
This reverts commit caac3057a14dce4ddaf645dd35d881a830612588.
This reverts commit 164d2f04af77c76957871b626b3e8484357f3a6a.
This reverts commit af3db056143ceb4afee339a504c0f619f89da792.
=> common: revert workarounds for QEMU segfaults

vagrant/bootstrap_scripts/rawhide-selinux.sh
With [0] merged we need to pull in libkmod explicitly; drop this once [1] lands in Fedora.
[0] https://github.com/systemd/systemd/pull/31131$
[1] https://github.com/dracut-ng/dracut-ng/pull/118
=> vagrant(rawhide): explicitly pull libkmod into the initrd

agent/testsuite-rhel9-sanitizers.sh
So adjust the $QEMU_SMP correctly there.
=> agent(rhel9): we run the tests w/ ASan parallelized in the RHEL9 job

vagrant/boxes/archlinux_systemd.sh
As 5.x is a bit broken, see https://savannah.gnu.org/bugs/?66171.
=> Downgrade screen to < 5.0.0

vagrant/boxes/rawhide_selinux.sh
Since it has broken signatures on current Rawhide.
See: https://pagure.io/releng/issue/12275
=> vagrant(rawhide): disable the openh264 repo

agent/bootstrap.sh
It currently has borked signatures and we don't need it to install systemd build deps anyway.
=> agent(upstream): temporarily disable crb-source repo

agent/bootstrap-rhel9.sh, agent/bootstrap.sh
Workaround for https://github.com/systemd/systemd/issues/34471
=> agent(upstream): pin tzdata to 2024a-2.el9.noarch

vagrant/boxes/rawhide_selinux.sh, vagrant/vagrant-setup.sh, vagrant/workarounds/build-shared-libs.sh
Vagrant requires this for its "synced folder" functionality. It does
this automagically during machine setup, but there appears to be some
bug in current Rawhide that breaks this process. Let's see if installing
the necessary tools beforehand makes any difference.
=> vagrant(rawhide): install NFS tools

vagrant/boxes/archlinux_systemd.sh, vagrant/vagrant-make-cache.sh
Since systemd/systemd@28dbee46d5bfdcfa601e80e248dbde22b8d65664 systemd-gpt-auto-generator now mounts ESP to /boot if it's empty, so let's drop some of the grub -> sd-boot migration shenanigans and let bootctl tell us where to put/expect stuff instead of guessing.
=> vagrant(arch): correctly detect where to put sd-boot entries
